/*
Deployment script for ASN6

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ASN6"
:setvar DefaultFilePrefix "ASN6"
:setvar DefaultDataPath "E:\SQL\DATA\"
:setvar DefaultLogPath "E:\SQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[fnSplit]...';


GO
-- =============================================
-- Author:		MECUNIC
-- Description:	FUNCIÓN SPLIT 
-- =============================================
CREATE FUNCTION [dbo].[fnSplit]
(	
	@sInputList VARCHAR(8000)
  , @sDelimiter VARCHAR(8000) = ','
) RETURNS @List TABLE (item VARCHAR(8000))

BEGIN
	DECLARE @sItem VARCHAR(8000)
	WHILE CHARINDEX(@sDelimiter,@sInputList,0) <> 0
	BEGIN
		SELECT
		@sItem=RTRIM(LTRIM(SUBSTRING(@sInputList,1,CHARINDEX(@sDelimiter,@sInputList,0)-1))),
		@sInputList=RTRIM(LTRIM(SUBSTRING(@sInputList,CHARINDEX(@sDelimiter,@sInputList,0)+LEN(@sDelimiter),LEN(@sInputList))))
 
		IF LEN(@sItem) > 0
			INSERT INTO @List SELECT @sItem
		END

	IF LEN(@sInputList) > 0
		INSERT INTO @List SELECT @sInputList -- Put the last item in
	RETURN
END
GO
PRINT N'Update complete.';


GO
