//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASNContext : DbContext
    {
        public ASNContext()
            : base("name=ASNContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<CatClientCMB_Result> CatClientCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClientCMB_Result>("CatClientCMB");
        }
    
        public virtual ObjectResult<CatConceptosCMB_Result> CatConceptosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosCMB_Result>("CatConceptosCMB");
        }
    
        public virtual ObjectResult<CatConceptosSel_Result> CatConceptosSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosSel_Result>("CatConceptosSel");
        }
    
        public virtual int CatConceptosSi(string descripcion, Nullable<int> tipoConcepto, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var tipoConceptoParameter = tipoConcepto.HasValue ?
                new ObjectParameter("TipoConcepto", tipoConcepto) :
                new ObjectParameter("TipoConcepto", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosSi", descripcionParameter, tipoConceptoParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatConceptosSu(Nullable<int> conceptoId, string descripcion, Nullable<int> tipoConcepto, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var conceptoIdParameter = conceptoId.HasValue ?
                new ObjectParameter("ConceptoId", conceptoId) :
                new ObjectParameter("ConceptoId", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var tipoConceptoParameter = tipoConcepto.HasValue ?
                new ObjectParameter("TipoConcepto", tipoConcepto) :
                new ObjectParameter("TipoConcepto", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosSu", conceptoIdParameter, descripcionParameter, tipoConceptoParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatCountryCMB_Result> CatCountryCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCountryCMB_Result>("CatCountryCMB");
        }
    
        public virtual ObjectResult<CatParametroConceptosCMB_Result> CatParametroConceptosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatParametroConceptosCMB_Result>("CatParametroConceptosCMB");
        }
    
        public virtual ObjectResult<CatPeriodicidadNominaCMB_Result> CatPeriodicidadNominaCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodicidadNominaCMB_Result>("CatPeriodicidadNominaCMB");
        }
    
        public virtual ObjectResult<CatPeriodicidadNominaSel_Result> CatPeriodicidadNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodicidadNominaSel_Result>("CatPeriodicidadNominaSel");
        }
    
        public virtual ObjectResult<CatProgramCMB_Result> CatProgramCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatProgramCMB_Result>("CatProgramCMB");
        }
    
        public virtual ObjectResult<CatRelUserRoleSel_Result> CatRelUserRoleSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatRelUserRoleSel_Result>("CatRelUserRoleSel", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatTipoConceptosCMB_Result> CatTipoConceptosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoConceptosCMB_Result>("CatTipoConceptosCMB");
        }
    
        public virtual ObjectResult<CatUserInfoSel_Result> CatUserInfoSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatUserInfoSel_Result>("CatUserInfoSel", cCMSIDParameter);
        }
    
        public virtual int CatLogErrorSi(string logErrorMessage, string stackTrace, string ipAddress, string browser, Nullable<int> createdBy)
        {
            var logErrorMessageParameter = logErrorMessage != null ?
                new ObjectParameter("LogErrorMessage", logErrorMessage) :
                new ObjectParameter("LogErrorMessage", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("IpAddress", ipAddress) :
                new ObjectParameter("IpAddress", typeof(string));
    
            var browserParameter = browser != null ?
                new ObjectParameter("Browser", browser) :
                new ObjectParameter("Browser", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatLogErrorSi", logErrorMessageParameter, stackTraceParameter, ipAddressParameter, browserParameter, createdByParameter);
        }
    
        public virtual int CatAñosNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAñosNominaSel");
        }
    
        public virtual int CatAñosNominaSi(Nullable<int> añoId, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var añoIdParameter = añoId.HasValue ?
                new ObjectParameter("AñoId", añoId) :
                new ObjectParameter("AñoId", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaCierreParameter = fechaCierre.HasValue ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(System.DateTime));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAñosNominaSi", añoIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatAñosNominaSu(Nullable<int> anioId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAñosNominaSu", anioIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatMesesNominaSel_Result> CatMesesNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMesesNominaSel_Result>("CatMesesNominaSel");
        }
    
        public virtual int CatPeriodosNominaSi(Nullable<int> anioId, Nullable<int> mesId, string periodicidadNominaId, string consecutivo, string tipoPeriodo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<System.DateTime> fechaCaptura, Nullable<System.DateTime> fechaCierre, string countryIdents, string nombrePeriodo, Nullable<int> userEmployeeId)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var consecutivoParameter = consecutivo != null ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(string));
    
            var tipoPeriodoParameter = tipoPeriodo != null ?
                new ObjectParameter("TipoPeriodo", tipoPeriodo) :
                new ObjectParameter("TipoPeriodo", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var fechaCapturaParameter = fechaCaptura.HasValue ?
                new ObjectParameter("FechaCaptura", fechaCaptura) :
                new ObjectParameter("FechaCaptura", typeof(System.DateTime));
    
            var fechaCierreParameter = fechaCierre.HasValue ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(System.DateTime));
    
            var countryIdentsParameter = countryIdents != null ?
                new ObjectParameter("CountryIdents", countryIdents) :
                new ObjectParameter("CountryIdents", typeof(string));
    
            var nombrePeriodoParameter = nombrePeriodo != null ?
                new ObjectParameter("NombrePeriodo", nombrePeriodo) :
                new ObjectParameter("NombrePeriodo", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodosNominaSi", anioIdParameter, mesIdParameter, periodicidadNominaIdParameter, consecutivoParameter, tipoPeriodoParameter, fechaInicioParameter, fechaFinParameter, fechaCapturaParameter, fechaCierreParameter, countryIdentsParameter, nombrePeriodoParameter, userEmployeeIdParameter);
        }
    
        public virtual ObjectResult<CatAniosNominaSel_Result> CatAniosNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAniosNominaSel_Result>("CatAniosNominaSel");
        }
    
        public virtual int CatAniosNominaSi(Nullable<int> anioId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAniosNominaSi", anioIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatAniosNominaSu(Nullable<int> anioId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAniosNominaSu", anioIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int CatMesesNominaSi(Nullable<int> anioId, Nullable<int> mesId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatMesesNominaSi", anioIdParameter, mesIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatMesesNominaSu(Nullable<int> anioId, Nullable<int> mesId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatMesesNominaSu", anioIdParameter, mesIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatAniosNominaCMB_Result> CatAniosNominaCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAniosNominaCMB_Result>("CatAniosNominaCMB");
        }
    
        public virtual ObjectResult<CatMesesCMB_Result> CatMesesCMB(Nullable<int> anioId)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMesesCMB_Result>("CatMesesCMB", anioIdParameter);
        }
    
        public virtual ObjectResult<CatConsecutivoPeriodicidadCMB_Result> CatConsecutivoPeriodicidadCMB(string catPeriodicidadNominaId)
        {
            var catPeriodicidadNominaIdParameter = catPeriodicidadNominaId != null ?
                new ObjectParameter("CatPeriodicidadNominaId", catPeriodicidadNominaId) :
                new ObjectParameter("CatPeriodicidadNominaId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConsecutivoPeriodicidadCMB_Result>("CatConsecutivoPeriodicidadCMB", catPeriodicidadNominaIdParameter);
        }
    
        public virtual ObjectResult<CatTiposPeriodoNominaCMB_Result> CatTiposPeriodoNominaCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTiposPeriodoNominaCMB_Result>("CatTiposPeriodoNominaCMB");
        }
    
        public virtual ObjectResult<CatTiposPeriodoNominaSel_Result> CatTiposPeriodoNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTiposPeriodoNominaSel_Result>("CatTiposPeriodoNominaSel");
        }
    
        public virtual int CatTiposPeriodoNominaSi(string tipoPeriodoId, string descripcion, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var tipoPeriodoIdParameter = tipoPeriodoId != null ?
                new ObjectParameter("TipoPeriodoId", tipoPeriodoId) :
                new ObjectParameter("TipoPeriodoId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatTiposPeriodoNominaSi", tipoPeriodoIdParameter, descripcionParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatTiposPeriodoNominaSu(string tipoPeriodoId, string descripcion, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var tipoPeriodoIdParameter = tipoPeriodoId != null ?
                new ObjectParameter("TipoPeriodoId", tipoPeriodoId) :
                new ObjectParameter("TipoPeriodoId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatTiposPeriodoNominaSu", tipoPeriodoIdParameter, descripcionParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatMesesFechasCMB_Result> CatMesesFechasCMB(Nullable<int> mesId, Nullable<int> anioId)
        {
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMesesFechasCMB_Result>("CatMesesFechasCMB", mesIdParameter, anioIdParameter);
        }
    
        public virtual ObjectResult<CatConceptosMotivoCMB_Result> CatConceptosMotivoCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosMotivoCMB_Result>("CatConceptosMotivoCMB");
        }
    
        public virtual ObjectResult<CatConceptosMotivosSel_Result> CatConceptosMotivosSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosMotivosSel_Result>("CatConceptosMotivosSel");
        }
    
        public virtual int CatConceptosMotivosSi(string descripcion, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosMotivosSi", descripcionParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatConceptosMotivosSu(Nullable<int> conceptoMotivoId, string descripcion, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var conceptoMotivoIdParameter = conceptoMotivoId.HasValue ?
                new ObjectParameter("ConceptoMotivoId", conceptoMotivoId) :
                new ObjectParameter("ConceptoMotivoId", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosMotivosSu", conceptoMotivoIdParameter, descripcionParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatAnioFechasCMB_Result> CatAnioFechasCMB(Nullable<int> anioId)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAnioFechasCMB_Result>("CatAnioFechasCMB", anioIdParameter);
        }
    
        public virtual int CatConsecutivoPeriodosSi(Nullable<int> anioId, Nullable<int> mesId, string consecutivoId, string periodicidadNominaId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var consecutivoIdParameter = consecutivoId != null ?
                new ObjectParameter("ConsecutivoId", consecutivoId) :
                new ObjectParameter("ConsecutivoId", typeof(string));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConsecutivoPeriodosSi", anioIdParameter, mesIdParameter, consecutivoIdParameter, periodicidadNominaIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatConsecutivoPeriodosSu(Nullable<int> anioId, Nullable<int> mesId, string consecutivoId, string periodicidadNominaId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var consecutivoIdParameter = consecutivoId != null ?
                new ObjectParameter("ConsecutivoId", consecutivoId) :
                new ObjectParameter("ConsecutivoId", typeof(string));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConsecutivoPeriodosSu", anioIdParameter, mesIdParameter, consecutivoIdParameter, periodicidadNominaIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual int CatConsecutivoPeriodicidadSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConsecutivoPeriodicidadSel");
        }
    
        public virtual ObjectResult<CatConsecutivoPeriodosSel_Result> CatConsecutivoPeriodosSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConsecutivoPeriodosSel_Result>("CatConsecutivoPeriodosSel");
        }
    
        public virtual int CatPeriodicidadNominaSi(string periodicidadNominaId, string descripcion, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodicidadNominaSi", periodicidadNominaIdParameter, descripcionParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatPeriodicidadNominaSu(string periodicidadNominaId, string descripcion, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodicidadNominaSu", periodicidadNominaIdParameter, descripcionParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatPeriodosNominaCMB_Result> CatPeriodosNominaCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodosNominaCMB_Result>("CatPeriodosNominaCMB");
        }
    
        public virtual int CatPeriodosNominaSu(Nullable<int> anioId, Nullable<int> mesId, string periodicidadNominaId, string consecutivo, string tipoPeriodo, string fechaInicio, string fechaFin, string fechaCaptura, string fechaCierre, string countryIdents, string nombrePeriodo, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var consecutivoParameter = consecutivo != null ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(string));
    
            var tipoPeriodoParameter = tipoPeriodo != null ?
                new ObjectParameter("TipoPeriodo", tipoPeriodo) :
                new ObjectParameter("TipoPeriodo", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            var fechaCapturaParameter = fechaCaptura != null ?
                new ObjectParameter("FechaCaptura", fechaCaptura) :
                new ObjectParameter("FechaCaptura", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var countryIdentsParameter = countryIdents != null ?
                new ObjectParameter("CountryIdents", countryIdents) :
                new ObjectParameter("CountryIdents", typeof(string));
    
            var nombrePeriodoParameter = nombrePeriodo != null ?
                new ObjectParameter("NombrePeriodo", nombrePeriodo) :
                new ObjectParameter("NombrePeriodo", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodosNominaSu", anioIdParameter, mesIdParameter, periodicidadNominaIdParameter, consecutivoParameter, tipoPeriodoParameter, fechaInicioParameter, fechaFinParameter, fechaCapturaParameter, fechaCierreParameter, countryIdentsParameter, nombrePeriodoParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatPeriodosNominaSel_Result> CatPeriodosNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodosNominaSel_Result>("CatPeriodosNominaSel");
        }
    
        public virtual ObjectResult<CatCountryVwCMB_Result> CatCountryVwCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCountryVwCMB_Result>("CatCountryVwCMB");
        }
    
        public virtual ObjectResult<CatPerfilEmpleadosCMB_Result> CatPerfilEmpleadosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPerfilEmpleadosCMB_Result>("CatPerfilEmpleadosCMB");
        }
    
        public virtual ObjectResult<CatPerfilEmpleadosSel_Result> CatPerfilEmpleadosSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPerfilEmpleadosSel_Result>("CatPerfilEmpleadosSel");
        }
    
        public virtual int CatPerfilEmpleadosSi(string nombrePerfilEmpleados, Nullable<int> country_Ident, string city_Ident, Nullable<int> company_Ident, Nullable<int> location_Ident, Nullable<int> client_Ident, Nullable<int> program_Ident, Nullable<int> contract_Type_Ident, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var nombrePerfilEmpleadosParameter = nombrePerfilEmpleados != null ?
                new ObjectParameter("NombrePerfilEmpleados", nombrePerfilEmpleados) :
                new ObjectParameter("NombrePerfilEmpleados", typeof(string));
    
            var country_IdentParameter = country_Ident.HasValue ?
                new ObjectParameter("Country_Ident", country_Ident) :
                new ObjectParameter("Country_Ident", typeof(int));
    
            var city_IdentParameter = city_Ident != null ?
                new ObjectParameter("City_Ident", city_Ident) :
                new ObjectParameter("City_Ident", typeof(string));
    
            var company_IdentParameter = company_Ident.HasValue ?
                new ObjectParameter("Company_Ident", company_Ident) :
                new ObjectParameter("Company_Ident", typeof(int));
    
            var location_IdentParameter = location_Ident.HasValue ?
                new ObjectParameter("Location_Ident", location_Ident) :
                new ObjectParameter("Location_Ident", typeof(int));
    
            var client_IdentParameter = client_Ident.HasValue ?
                new ObjectParameter("Client_Ident", client_Ident) :
                new ObjectParameter("Client_Ident", typeof(int));
    
            var program_IdentParameter = program_Ident.HasValue ?
                new ObjectParameter("Program_Ident", program_Ident) :
                new ObjectParameter("Program_Ident", typeof(int));
    
            var contract_Type_IdentParameter = contract_Type_Ident.HasValue ?
                new ObjectParameter("Contract_Type_Ident", contract_Type_Ident) :
                new ObjectParameter("Contract_Type_Ident", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPerfilEmpleadosSi", nombrePerfilEmpleadosParameter, country_IdentParameter, city_IdentParameter, company_IdentParameter, location_IdentParameter, client_IdentParameter, program_IdentParameter, contract_Type_IdentParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatPerfilEmpleadosSu(Nullable<int> perfil_Ident, string nombrePerfilEmpleados, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            var nombrePerfilEmpleadosParameter = nombrePerfilEmpleados != null ?
                new ObjectParameter("NombrePerfilEmpleados", nombrePerfilEmpleados) :
                new ObjectParameter("NombrePerfilEmpleados", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPerfilEmpleadosSu", perfil_IdentParameter, nombrePerfilEmpleadosParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatCityCMB_Result> CatCityCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCityCMB_Result>("CatCityCMB");
        }
    
        public virtual ObjectResult<CatCompanyCMB_Result> CatCompanyCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCompanyCMB_Result>("CatCompanyCMB");
        }
    
        public virtual ObjectResult<CatContractTypeCMB_Result> CatContractTypeCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatContractTypeCMB_Result>("CatContractTypeCMB");
        }
    
        public virtual ObjectResult<CatLocationCMB_Result> CatLocationCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatLocationCMB_Result>("CatLocationCMB");
        }
    
        public virtual ObjectResult<Nullable<int>> CatPeriodoNominaFechasCMB(Nullable<int> anioId, Nullable<int> mesId, string consecutivoId, string periodicidadNominaId, string tipoPeriodo, string nombrePeriodo)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var consecutivoIdParameter = consecutivoId != null ?
                new ObjectParameter("ConsecutivoId", consecutivoId) :
                new ObjectParameter("ConsecutivoId", typeof(string));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var tipoPeriodoParameter = tipoPeriodo != null ?
                new ObjectParameter("TipoPeriodo", tipoPeriodo) :
                new ObjectParameter("TipoPeriodo", typeof(string));
    
            var nombrePeriodoParameter = nombrePeriodo != null ?
                new ObjectParameter("NombrePeriodo", nombrePeriodo) :
                new ObjectParameter("NombrePeriodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CatPeriodoNominaFechasCMB", anioIdParameter, mesIdParameter, consecutivoIdParameter, periodicidadNominaIdParameter, tipoPeriodoParameter, nombrePeriodoParameter);
        }
    }
}
