//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASNContext : DbContext
    {
        public ASNContext()
            : base("name=ASNContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<CatClientCMB_Result> CatClientCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClientCMB_Result>("CatClientCMB");
        }
    
        public virtual ObjectResult<CatConceptosCMB_Result> CatConceptosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosCMB_Result>("CatConceptosCMB");
        }
    
        public virtual ObjectResult<CatConceptosSel_Result> CatConceptosSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosSel_Result>("CatConceptosSel");
        }
    
        public virtual int CatConceptosSi(string descripcion, Nullable<int> tipoConcepto, string paisId, Nullable<int> mercadoId, Nullable<int> clienteId, Nullable<int> peopleSoftId, Nullable<int> numeroNivelAutorizante, Nullable<bool> autorizacionAutomatica, Nullable<bool> autorizacionObligatoria, string vigencia, Nullable<bool> pagosFijos, Nullable<decimal> tope, string periodicidadNominaId, string fechaInicio, string fechaFin, Nullable<int> parametroConceptoId, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var tipoConceptoParameter = tipoConcepto.HasValue ?
                new ObjectParameter("TipoConcepto", tipoConcepto) :
                new ObjectParameter("TipoConcepto", typeof(int));
    
            var paisIdParameter = paisId != null ?
                new ObjectParameter("PaisId", paisId) :
                new ObjectParameter("PaisId", typeof(string));
    
            var mercadoIdParameter = mercadoId.HasValue ?
                new ObjectParameter("MercadoId", mercadoId) :
                new ObjectParameter("MercadoId", typeof(int));
    
            var clienteIdParameter = clienteId.HasValue ?
                new ObjectParameter("ClienteId", clienteId) :
                new ObjectParameter("ClienteId", typeof(int));
    
            var peopleSoftIdParameter = peopleSoftId.HasValue ?
                new ObjectParameter("PeopleSoftId", peopleSoftId) :
                new ObjectParameter("PeopleSoftId", typeof(int));
    
            var numeroNivelAutorizanteParameter = numeroNivelAutorizante.HasValue ?
                new ObjectParameter("NumeroNivelAutorizante", numeroNivelAutorizante) :
                new ObjectParameter("NumeroNivelAutorizante", typeof(int));
    
            var autorizacionAutomaticaParameter = autorizacionAutomatica.HasValue ?
                new ObjectParameter("AutorizacionAutomatica", autorizacionAutomatica) :
                new ObjectParameter("AutorizacionAutomatica", typeof(bool));
    
            var autorizacionObligatoriaParameter = autorizacionObligatoria.HasValue ?
                new ObjectParameter("AutorizacionObligatoria", autorizacionObligatoria) :
                new ObjectParameter("AutorizacionObligatoria", typeof(bool));
    
            var vigenciaParameter = vigencia != null ?
                new ObjectParameter("Vigencia", vigencia) :
                new ObjectParameter("Vigencia", typeof(string));
    
            var pagosFijosParameter = pagosFijos.HasValue ?
                new ObjectParameter("PagosFijos", pagosFijos) :
                new ObjectParameter("PagosFijos", typeof(bool));
    
            var topeParameter = tope.HasValue ?
                new ObjectParameter("Tope", tope) :
                new ObjectParameter("Tope", typeof(decimal));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            var parametroConceptoIdParameter = parametroConceptoId.HasValue ?
                new ObjectParameter("ParametroConceptoId", parametroConceptoId) :
                new ObjectParameter("ParametroConceptoId", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosSi", descripcionParameter, tipoConceptoParameter, paisIdParameter, mercadoIdParameter, clienteIdParameter, peopleSoftIdParameter, numeroNivelAutorizanteParameter, autorizacionAutomaticaParameter, autorizacionObligatoriaParameter, vigenciaParameter, pagosFijosParameter, topeParameter, periodicidadNominaIdParameter, fechaInicioParameter, fechaFinParameter, parametroConceptoIdParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatConceptosSu(Nullable<int> conceptoId, string descripcion, Nullable<int> tipoConcepto, string paisId, Nullable<int> mercadoId, Nullable<int> clienteId, Nullable<int> peopleSoftId, Nullable<int> numeroNivelAutorizante, Nullable<bool> autorizacionAutomatica, Nullable<bool> autorizacionObligatoria, string vigencia, Nullable<bool> pagosFijos, Nullable<decimal> tope, string periodicidadNominaId, string fechaInicio, string fechaFin, Nullable<int> parametroConceptoId, Nullable<bool> active, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var conceptoIdParameter = conceptoId.HasValue ?
                new ObjectParameter("ConceptoId", conceptoId) :
                new ObjectParameter("ConceptoId", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var tipoConceptoParameter = tipoConcepto.HasValue ?
                new ObjectParameter("TipoConcepto", tipoConcepto) :
                new ObjectParameter("TipoConcepto", typeof(int));
    
            var paisIdParameter = paisId != null ?
                new ObjectParameter("PaisId", paisId) :
                new ObjectParameter("PaisId", typeof(string));
    
            var mercadoIdParameter = mercadoId.HasValue ?
                new ObjectParameter("MercadoId", mercadoId) :
                new ObjectParameter("MercadoId", typeof(int));
    
            var clienteIdParameter = clienteId.HasValue ?
                new ObjectParameter("ClienteId", clienteId) :
                new ObjectParameter("ClienteId", typeof(int));
    
            var peopleSoftIdParameter = peopleSoftId.HasValue ?
                new ObjectParameter("PeopleSoftId", peopleSoftId) :
                new ObjectParameter("PeopleSoftId", typeof(int));
    
            var numeroNivelAutorizanteParameter = numeroNivelAutorizante.HasValue ?
                new ObjectParameter("NumeroNivelAutorizante", numeroNivelAutorizante) :
                new ObjectParameter("NumeroNivelAutorizante", typeof(int));
    
            var autorizacionAutomaticaParameter = autorizacionAutomatica.HasValue ?
                new ObjectParameter("AutorizacionAutomatica", autorizacionAutomatica) :
                new ObjectParameter("AutorizacionAutomatica", typeof(bool));
    
            var autorizacionObligatoriaParameter = autorizacionObligatoria.HasValue ?
                new ObjectParameter("AutorizacionObligatoria", autorizacionObligatoria) :
                new ObjectParameter("AutorizacionObligatoria", typeof(bool));
    
            var vigenciaParameter = vigencia != null ?
                new ObjectParameter("Vigencia", vigencia) :
                new ObjectParameter("Vigencia", typeof(string));
    
            var pagosFijosParameter = pagosFijos.HasValue ?
                new ObjectParameter("PagosFijos", pagosFijos) :
                new ObjectParameter("PagosFijos", typeof(bool));
    
            var topeParameter = tope.HasValue ?
                new ObjectParameter("Tope", tope) :
                new ObjectParameter("Tope", typeof(decimal));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            var parametroConceptoIdParameter = parametroConceptoId.HasValue ?
                new ObjectParameter("ParametroConceptoId", parametroConceptoId) :
                new ObjectParameter("ParametroConceptoId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosSu", conceptoIdParameter, descripcionParameter, tipoConceptoParameter, paisIdParameter, mercadoIdParameter, clienteIdParameter, peopleSoftIdParameter, numeroNivelAutorizanteParameter, autorizacionAutomaticaParameter, autorizacionObligatoriaParameter, vigenciaParameter, pagosFijosParameter, topeParameter, periodicidadNominaIdParameter, fechaInicioParameter, fechaFinParameter, parametroConceptoIdParameter, activeParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual ObjectResult<CatCountryCMB_Result> CatCountryCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCountryCMB_Result>("CatCountryCMB");
        }
    
        public virtual ObjectResult<CatParametroConceptosCMB_Result> CatParametroConceptosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatParametroConceptosCMB_Result>("CatParametroConceptosCMB");
        }
    
        public virtual ObjectResult<CatPeriodicidadNominaCMB_Result> CatPeriodicidadNominaCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodicidadNominaCMB_Result>("CatPeriodicidadNominaCMB");
        }
    
        public virtual ObjectResult<CatPeriodicidadNominaSel_Result> CatPeriodicidadNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodicidadNominaSel_Result>("CatPeriodicidadNominaSel");
        }
    
        public virtual ObjectResult<CatProgramCMB_Result> CatProgramCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatProgramCMB_Result>("CatProgramCMB");
        }
    
        public virtual ObjectResult<CatRelUserRoleSel_Result> CatRelUserRoleSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatRelUserRoleSel_Result>("CatRelUserRoleSel", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatTipoConceptosCMB_Result> CatTipoConceptosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoConceptosCMB_Result>("CatTipoConceptosCMB");
        }
    
        public virtual ObjectResult<CatUserInfoSel_Result> CatUserInfoSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatUserInfoSel_Result>("CatUserInfoSel", cCMSIDParameter);
        }
    
        public virtual int CatLogErrorSi(string logErrorMessage, string stackTrace, string ipAddress, string browser, Nullable<int> createdBy)
        {
            var logErrorMessageParameter = logErrorMessage != null ?
                new ObjectParameter("LogErrorMessage", logErrorMessage) :
                new ObjectParameter("LogErrorMessage", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("IpAddress", ipAddress) :
                new ObjectParameter("IpAddress", typeof(string));
    
            var browserParameter = browser != null ?
                new ObjectParameter("Browser", browser) :
                new ObjectParameter("Browser", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatLogErrorSi", logErrorMessageParameter, stackTraceParameter, ipAddressParameter, browserParameter, createdByParameter);
        }
    
        public virtual int CatAñosNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAñosNominaSel");
        }
    
        public virtual int CatAñosNominaSi(Nullable<int> añoId, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var añoIdParameter = añoId.HasValue ?
                new ObjectParameter("AñoId", añoId) :
                new ObjectParameter("AñoId", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaCierreParameter = fechaCierre.HasValue ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(System.DateTime));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAñosNominaSi", añoIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatAñosNominaSu(Nullable<int> anioId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAñosNominaSu", anioIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatMesesNominaSel_Result> CatMesesNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMesesNominaSel_Result>("CatMesesNominaSel");
        }
    
        public virtual int CatPeriodosNominaSi(Nullable<int> anioId, Nullable<int> mesId, string periodicidadNominaId, string consecutivo, string tipoPeriodo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<System.DateTime> fechaCaptura, Nullable<System.DateTime> fechaCierre, string countryIdents, string nombrePeriodo, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var consecutivoParameter = consecutivo != null ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(string));
    
            var tipoPeriodoParameter = tipoPeriodo != null ?
                new ObjectParameter("TipoPeriodo", tipoPeriodo) :
                new ObjectParameter("TipoPeriodo", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var fechaCapturaParameter = fechaCaptura.HasValue ?
                new ObjectParameter("FechaCaptura", fechaCaptura) :
                new ObjectParameter("FechaCaptura", typeof(System.DateTime));
    
            var fechaCierreParameter = fechaCierre.HasValue ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(System.DateTime));
    
            var countryIdentsParameter = countryIdents != null ?
                new ObjectParameter("CountryIdents", countryIdents) :
                new ObjectParameter("CountryIdents", typeof(string));
    
            var nombrePeriodoParameter = nombrePeriodo != null ?
                new ObjectParameter("NombrePeriodo", nombrePeriodo) :
                new ObjectParameter("NombrePeriodo", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodosNominaSi", anioIdParameter, mesIdParameter, periodicidadNominaIdParameter, consecutivoParameter, tipoPeriodoParameter, fechaInicioParameter, fechaFinParameter, fechaCapturaParameter, fechaCierreParameter, countryIdentsParameter, nombrePeriodoParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual ObjectResult<CatAniosNominaSel_Result> CatAniosNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAniosNominaSel_Result>("CatAniosNominaSel");
        }
    
        public virtual int CatAniosNominaSi(Nullable<int> anioId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAniosNominaSi", anioIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatAniosNominaSu(Nullable<int> anioId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatAniosNominaSu", anioIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int CatMesesNominaSi(Nullable<int> anioId, Nullable<int> mesId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatMesesNominaSi", anioIdParameter, mesIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatMesesNominaSu(Nullable<int> anioId, Nullable<int> mesId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatMesesNominaSu", anioIdParameter, mesIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatAniosNominaCMB_Result> CatAniosNominaCMB(Nullable<int> anioActivo)
        {
            var anioActivoParameter = anioActivo.HasValue ?
                new ObjectParameter("AnioActivo", anioActivo) :
                new ObjectParameter("AnioActivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAniosNominaCMB_Result>("CatAniosNominaCMB", anioActivoParameter);
        }
    
        public virtual ObjectResult<CatMesesCMB_Result> CatMesesCMB(Nullable<int> anioId)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMesesCMB_Result>("CatMesesCMB", anioIdParameter);
        }
    
        public virtual ObjectResult<CatConsecutivoPeriodicidadCMB_Result> CatConsecutivoPeriodicidadCMB(string catPeriodicidadNominaId)
        {
            var catPeriodicidadNominaIdParameter = catPeriodicidadNominaId != null ?
                new ObjectParameter("CatPeriodicidadNominaId", catPeriodicidadNominaId) :
                new ObjectParameter("CatPeriodicidadNominaId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConsecutivoPeriodicidadCMB_Result>("CatConsecutivoPeriodicidadCMB", catPeriodicidadNominaIdParameter);
        }
    
        public virtual ObjectResult<CatTiposPeriodoNominaCMB_Result> CatTiposPeriodoNominaCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTiposPeriodoNominaCMB_Result>("CatTiposPeriodoNominaCMB");
        }
    
        public virtual ObjectResult<CatTiposPeriodoNominaSel_Result> CatTiposPeriodoNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTiposPeriodoNominaSel_Result>("CatTiposPeriodoNominaSel");
        }
    
        public virtual int CatTiposPeriodoNominaSi(string tipoPeriodoId, string descripcion, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var tipoPeriodoIdParameter = tipoPeriodoId != null ?
                new ObjectParameter("TipoPeriodoId", tipoPeriodoId) :
                new ObjectParameter("TipoPeriodoId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatTiposPeriodoNominaSi", tipoPeriodoIdParameter, descripcionParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatTiposPeriodoNominaSu(string tipoPeriodoId, string descripcion, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var tipoPeriodoIdParameter = tipoPeriodoId != null ?
                new ObjectParameter("TipoPeriodoId", tipoPeriodoId) :
                new ObjectParameter("TipoPeriodoId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatTiposPeriodoNominaSu", tipoPeriodoIdParameter, descripcionParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatMesesFechasCMB_Result> CatMesesFechasCMB(Nullable<int> mesId, Nullable<int> anioId)
        {
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMesesFechasCMB_Result>("CatMesesFechasCMB", mesIdParameter, anioIdParameter);
        }
    
        public virtual ObjectResult<CatConceptosMotivoCMB_Result> CatConceptosMotivoCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosMotivoCMB_Result>("CatConceptosMotivoCMB");
        }
    
        public virtual ObjectResult<CatConceptosMotivosSel_Result> CatConceptosMotivosSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConceptosMotivosSel_Result>("CatConceptosMotivosSel");
        }
    
        public virtual int CatConceptosMotivosSi(string descripcion, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosMotivosSi", descripcionParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatConceptosMotivosSu(Nullable<int> conceptoMotivoId, string descripcion, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var conceptoMotivoIdParameter = conceptoMotivoId.HasValue ?
                new ObjectParameter("ConceptoMotivoId", conceptoMotivoId) :
                new ObjectParameter("ConceptoMotivoId", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConceptosMotivosSu", conceptoMotivoIdParameter, descripcionParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatAnioFechasCMB_Result> CatAnioFechasCMB(Nullable<int> anioId)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAnioFechasCMB_Result>("CatAnioFechasCMB", anioIdParameter);
        }
    
        public virtual int CatConsecutivoPeriodosSi(Nullable<int> anioId, Nullable<int> mesId, string consecutivoId, string periodicidadNominaId, Nullable<int> tipoConsecutivoId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var consecutivoIdParameter = consecutivoId != null ?
                new ObjectParameter("ConsecutivoId", consecutivoId) :
                new ObjectParameter("ConsecutivoId", typeof(string));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var tipoConsecutivoIdParameter = tipoConsecutivoId.HasValue ?
                new ObjectParameter("TipoConsecutivoId", tipoConsecutivoId) :
                new ObjectParameter("TipoConsecutivoId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConsecutivoPeriodosSi", anioIdParameter, mesIdParameter, consecutivoIdParameter, periodicidadNominaIdParameter, tipoConsecutivoIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatConsecutivoPeriodosSu(Nullable<int> anioId, Nullable<int> mesId, string consecutivoId, string periodicidadNominaId, Nullable<int> tipoConsecutivoId, string fechaInicio, string fechaCierre, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var consecutivoIdParameter = consecutivoId != null ?
                new ObjectParameter("ConsecutivoId", consecutivoId) :
                new ObjectParameter("ConsecutivoId", typeof(string));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var tipoConsecutivoIdParameter = tipoConsecutivoId.HasValue ?
                new ObjectParameter("TipoConsecutivoId", tipoConsecutivoId) :
                new ObjectParameter("TipoConsecutivoId", typeof(int));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConsecutivoPeriodosSu", anioIdParameter, mesIdParameter, consecutivoIdParameter, periodicidadNominaIdParameter, tipoConsecutivoIdParameter, fechaInicioParameter, fechaCierreParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual int CatConsecutivoPeriodicidadSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatConsecutivoPeriodicidadSel");
        }
    
        public virtual ObjectResult<CatConsecutivoPeriodosSel_Result> CatConsecutivoPeriodosSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatConsecutivoPeriodosSel_Result>("CatConsecutivoPeriodosSel");
        }
    
        public virtual int CatPeriodicidadNominaSi(string periodicidadNominaId, string descripcion, Nullable<int> consecutivos, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var consecutivosParameter = consecutivos.HasValue ?
                new ObjectParameter("Consecutivos", consecutivos) :
                new ObjectParameter("Consecutivos", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodicidadNominaSi", periodicidadNominaIdParameter, descripcionParameter, consecutivosParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatPeriodicidadNominaSu(string periodicidadNominaId, string descripcion, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodicidadNominaSu", periodicidadNominaIdParameter, descripcionParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatPeriodosNominaCMB_Result> CatPeriodosNominaCMB(Nullable<int> active)
        {
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodosNominaCMB_Result>("CatPeriodosNominaCMB", activeParameter);
        }
    
        public virtual int CatPeriodosNominaSu(Nullable<int> anioId, Nullable<int> mesId, string periodicidadNominaId, string consecutivo, string tipoPeriodo, string fechaInicio, string fechaFin, string fechaCaptura, string fechaCierre, string countryIdents, string nombrePeriodo, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var consecutivoParameter = consecutivo != null ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(string));
    
            var tipoPeriodoParameter = tipoPeriodo != null ?
                new ObjectParameter("TipoPeriodo", tipoPeriodo) :
                new ObjectParameter("TipoPeriodo", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            var fechaCapturaParameter = fechaCaptura != null ?
                new ObjectParameter("FechaCaptura", fechaCaptura) :
                new ObjectParameter("FechaCaptura", typeof(string));
    
            var fechaCierreParameter = fechaCierre != null ?
                new ObjectParameter("FechaCierre", fechaCierre) :
                new ObjectParameter("FechaCierre", typeof(string));
    
            var countryIdentsParameter = countryIdents != null ?
                new ObjectParameter("CountryIdents", countryIdents) :
                new ObjectParameter("CountryIdents", typeof(string));
    
            var nombrePeriodoParameter = nombrePeriodo != null ?
                new ObjectParameter("NombrePeriodo", nombrePeriodo) :
                new ObjectParameter("NombrePeriodo", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPeriodosNominaSu", anioIdParameter, mesIdParameter, periodicidadNominaIdParameter, consecutivoParameter, tipoPeriodoParameter, fechaInicioParameter, fechaFinParameter, fechaCapturaParameter, fechaCierreParameter, countryIdentsParameter, nombrePeriodoParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatPeriodosNominaSel_Result> CatPeriodosNominaSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodosNominaSel_Result>("CatPeriodosNominaSel");
        }
    
        public virtual ObjectResult<CatCountryVwCMB_Result> CatCountryVwCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCountryVwCMB_Result>("CatCountryVwCMB");
        }
    
        public virtual ObjectResult<CatPerfilEmpleadosCMB_Result> CatPerfilEmpleadosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPerfilEmpleadosCMB_Result>("CatPerfilEmpleadosCMB");
        }
    
        public virtual int CatPerfilEmpleadosSi(string nombrePerfilEmpleados, Nullable<int> country_Ident, string city_Ident, Nullable<int> company_Ident, Nullable<int> location_Ident, Nullable<int> client_Ident, Nullable<int> program_Ident, Nullable<int> contract_Type_Ident, Nullable<int> conceptoId, Nullable<int> tipoAccesoId, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var nombrePerfilEmpleadosParameter = nombrePerfilEmpleados != null ?
                new ObjectParameter("NombrePerfilEmpleados", nombrePerfilEmpleados) :
                new ObjectParameter("NombrePerfilEmpleados", typeof(string));
    
            var country_IdentParameter = country_Ident.HasValue ?
                new ObjectParameter("Country_Ident", country_Ident) :
                new ObjectParameter("Country_Ident", typeof(int));
    
            var city_IdentParameter = city_Ident != null ?
                new ObjectParameter("City_Ident", city_Ident) :
                new ObjectParameter("City_Ident", typeof(string));
    
            var company_IdentParameter = company_Ident.HasValue ?
                new ObjectParameter("Company_Ident", company_Ident) :
                new ObjectParameter("Company_Ident", typeof(int));
    
            var location_IdentParameter = location_Ident.HasValue ?
                new ObjectParameter("Location_Ident", location_Ident) :
                new ObjectParameter("Location_Ident", typeof(int));
    
            var client_IdentParameter = client_Ident.HasValue ?
                new ObjectParameter("Client_Ident", client_Ident) :
                new ObjectParameter("Client_Ident", typeof(int));
    
            var program_IdentParameter = program_Ident.HasValue ?
                new ObjectParameter("Program_Ident", program_Ident) :
                new ObjectParameter("Program_Ident", typeof(int));
    
            var contract_Type_IdentParameter = contract_Type_Ident.HasValue ?
                new ObjectParameter("Contract_Type_Ident", contract_Type_Ident) :
                new ObjectParameter("Contract_Type_Ident", typeof(int));
    
            var conceptoIdParameter = conceptoId.HasValue ?
                new ObjectParameter("ConceptoId", conceptoId) :
                new ObjectParameter("ConceptoId", typeof(int));
    
            var tipoAccesoIdParameter = tipoAccesoId.HasValue ?
                new ObjectParameter("TipoAccesoId", tipoAccesoId) :
                new ObjectParameter("TipoAccesoId", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPerfilEmpleadosSi", nombrePerfilEmpleadosParameter, country_IdentParameter, city_IdentParameter, company_IdentParameter, location_IdentParameter, client_IdentParameter, program_IdentParameter, contract_Type_IdentParameter, conceptoIdParameter, tipoAccesoIdParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatPerfilEmpleadosSu(Nullable<int> perfil_Ident, string nombrePerfilEmpleados, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            var nombrePerfilEmpleadosParameter = nombrePerfilEmpleados != null ?
                new ObjectParameter("NombrePerfilEmpleados", nombrePerfilEmpleados) :
                new ObjectParameter("NombrePerfilEmpleados", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPerfilEmpleadosSu", perfil_IdentParameter, nombrePerfilEmpleadosParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual ObjectResult<CatCityCMB_Result> CatCityCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCityCMB_Result>("CatCityCMB");
        }
    
        public virtual ObjectResult<CatCompanyCMB_Result> CatCompanyCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCompanyCMB_Result>("CatCompanyCMB");
        }
    
        public virtual ObjectResult<CatContractTypeCMB_Result> CatContractTypeCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatContractTypeCMB_Result>("CatContractTypeCMB");
        }
    
        public virtual ObjectResult<CatLocationCMB_Result> CatLocationCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatLocationCMB_Result>("CatLocationCMB");
        }
    
        public virtual ObjectResult<Nullable<int>> CatPeriodoNominaFechasCMB(Nullable<int> anioId, Nullable<int> mesId, string consecutivoId, string periodicidadNominaId, string tipoPeriodo, string nombrePeriodo)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            var mesIdParameter = mesId.HasValue ?
                new ObjectParameter("MesId", mesId) :
                new ObjectParameter("MesId", typeof(int));
    
            var consecutivoIdParameter = consecutivoId != null ?
                new ObjectParameter("ConsecutivoId", consecutivoId) :
                new ObjectParameter("ConsecutivoId", typeof(string));
    
            var periodicidadNominaIdParameter = periodicidadNominaId != null ?
                new ObjectParameter("PeriodicidadNominaId", periodicidadNominaId) :
                new ObjectParameter("PeriodicidadNominaId", typeof(string));
    
            var tipoPeriodoParameter = tipoPeriodo != null ?
                new ObjectParameter("TipoPeriodo", tipoPeriodo) :
                new ObjectParameter("TipoPeriodo", typeof(string));
    
            var nombrePeriodoParameter = nombrePeriodo != null ?
                new ObjectParameter("NombrePeriodo", nombrePeriodo) :
                new ObjectParameter("NombrePeriodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CatPeriodoNominaFechasCMB", anioIdParameter, mesIdParameter, consecutivoIdParameter, periodicidadNominaIdParameter, tipoPeriodoParameter, nombrePeriodoParameter);
        }
    
        public virtual ObjectResult<CatAnioMesesConsecutivoCMB_Result> CatAnioMesesConsecutivoCMB(Nullable<int> anioId)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("AnioId", anioId) :
                new ObjectParameter("AnioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAnioMesesConsecutivoCMB_Result>("CatAnioMesesConsecutivoCMB", anioIdParameter);
        }
    
        public virtual ObjectResult<CatAnioMesPeriodicidadNominaCMB_Result> CatAnioMesPeriodicidadNominaCMB(Nullable<int> anioId, string mesId)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("anioId", anioId) :
                new ObjectParameter("anioId", typeof(int));
    
            var mesIdParameter = mesId != null ?
                new ObjectParameter("mesId", mesId) :
                new ObjectParameter("mesId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAnioMesPeriodicidadNominaCMB_Result>("CatAnioMesPeriodicidadNominaCMB", anioIdParameter, mesIdParameter);
        }
    
        public virtual ObjectResult<CatTiposAccesoCMB_Result> CatTiposAccesoCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTiposAccesoCMB_Result>("CatTiposAccesoCMB");
        }
    
        public virtual ObjectResult<CatTiposConsecutivoCMB_Result> CatTiposConsecutivoCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTiposConsecutivoCMB_Result>("CatTiposConsecutivoCMB");
        }
    
        public virtual ObjectResult<CatPeriodicidadNominaAnioMesConsecutivoCMB_Result> CatPeriodicidadNominaAnioMesConsecutivoCMB(Nullable<int> anioId, string mesId, string periodicidadNomina)
        {
            var anioIdParameter = anioId.HasValue ?
                new ObjectParameter("anioId", anioId) :
                new ObjectParameter("anioId", typeof(int));
    
            var mesIdParameter = mesId != null ?
                new ObjectParameter("mesId", mesId) :
                new ObjectParameter("mesId", typeof(string));
    
            var periodicidadNominaParameter = periodicidadNomina != null ?
                new ObjectParameter("PeriodicidadNomina", periodicidadNomina) :
                new ObjectParameter("PeriodicidadNomina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPeriodicidadNominaAnioMesConsecutivoCMB_Result>("CatPeriodicidadNominaAnioMesConsecutivoCMB", anioIdParameter, mesIdParameter, periodicidadNominaParameter);
        }
    
        public virtual ObjectResult<CatCityTodosCMB_Result> CatCityTodosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCityTodosCMB_Result>("CatCityTodosCMB");
        }
    
        public virtual ObjectResult<CatClientTodosCMB_Result> CatClientTodosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClientTodosCMB_Result>("CatClientTodosCMB");
        }
    
        public virtual ObjectResult<CatCompanyTodosCMB_Result> CatCompanyTodosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCompanyTodosCMB_Result>("CatCompanyTodosCMB");
        }
    
        public virtual ObjectResult<CatContractTypeTodosCMB_Result> CatContractTypeTodosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatContractTypeTodosCMB_Result>("CatContractTypeTodosCMB");
        }
    
        public virtual ObjectResult<CatCountryTodosCMB_Result> CatCountryTodosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCountryTodosCMB_Result>("CatCountryTodosCMB");
        }
    
        public virtual ObjectResult<CatLocationTodosCMB_Result> CatLocationTodosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatLocationTodosCMB_Result>("CatLocationTodosCMB");
        }
    
        public virtual ObjectResult<CatProgramTodosCMB_Result> CatProgramTodosCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatProgramTodosCMB_Result>("CatProgramTodosCMB");
        }
    
        public virtual ObjectResult<CatPerfilEmpleadosSel_Result> CatPerfilEmpleadosSel(Nullable<int> perfil_Ident)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPerfilEmpleadosSel_Result>("CatPerfilEmpleadosSel", perfil_IdentParameter);
        }
    
        public virtual int CargaPivote(Nullable<int> consecutivo)
        {
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CargaPivote", consecutivoParameter);
        }
    
        public virtual ObjectResult<CatEmployeeSel_Result> CatEmployeeSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeSel_Result>("CatEmployeeSel");
        }
    
        public virtual ObjectResult<EmpleadosxPerfilSel_Result> EmpleadosxPerfilSel(Nullable<int> perfil_Ident)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpleadosxPerfilSel_Result>("EmpleadosxPerfilSel", perfil_IdentParameter);
        }
    
        public virtual int CatSolicitudesSu(Nullable<int> folioSolicitud, Nullable<System.DateTime> fecha_Solicitud, Nullable<int> perfil_Ident, Nullable<int> solicitante_Ident, string solicintante_Nombre, Nullable<int> puesto_solicitante_Ident, string periodoNomina_Id, string periodoNominaOriginal_Id, Nullable<int> conceptoId, Nullable<int> motivoId, string justficacion, Nullable<int> responsable_Id, Nullable<int> detalle, string autorizantes, ObjectParameter estatus, Nullable<int> userEmployeeId)
        {
            var folioSolicitudParameter = folioSolicitud.HasValue ?
                new ObjectParameter("FolioSolicitud", folioSolicitud) :
                new ObjectParameter("FolioSolicitud", typeof(int));
    
            var fecha_SolicitudParameter = fecha_Solicitud.HasValue ?
                new ObjectParameter("Fecha_Solicitud", fecha_Solicitud) :
                new ObjectParameter("Fecha_Solicitud", typeof(System.DateTime));
    
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            var solicitante_IdentParameter = solicitante_Ident.HasValue ?
                new ObjectParameter("Solicitante_Ident", solicitante_Ident) :
                new ObjectParameter("Solicitante_Ident", typeof(int));
    
            var solicintante_NombreParameter = solicintante_Nombre != null ?
                new ObjectParameter("Solicintante_Nombre", solicintante_Nombre) :
                new ObjectParameter("Solicintante_Nombre", typeof(string));
    
            var puesto_solicitante_IdentParameter = puesto_solicitante_Ident.HasValue ?
                new ObjectParameter("Puesto_solicitante_Ident", puesto_solicitante_Ident) :
                new ObjectParameter("Puesto_solicitante_Ident", typeof(int));
    
            var periodoNomina_IdParameter = periodoNomina_Id != null ?
                new ObjectParameter("PeriodoNomina_Id", periodoNomina_Id) :
                new ObjectParameter("PeriodoNomina_Id", typeof(string));
    
            var periodoNominaOriginal_IdParameter = periodoNominaOriginal_Id != null ?
                new ObjectParameter("PeriodoNominaOriginal_Id", periodoNominaOriginal_Id) :
                new ObjectParameter("PeriodoNominaOriginal_Id", typeof(string));
    
            var conceptoIdParameter = conceptoId.HasValue ?
                new ObjectParameter("ConceptoId", conceptoId) :
                new ObjectParameter("ConceptoId", typeof(int));
    
            var motivoIdParameter = motivoId.HasValue ?
                new ObjectParameter("MotivoId", motivoId) :
                new ObjectParameter("MotivoId", typeof(int));
    
            var justficacionParameter = justficacion != null ?
                new ObjectParameter("Justficacion", justficacion) :
                new ObjectParameter("Justficacion", typeof(string));
    
            var responsable_IdParameter = responsable_Id.HasValue ?
                new ObjectParameter("Responsable_Id", responsable_Id) :
                new ObjectParameter("Responsable_Id", typeof(int));
    
            var detalleParameter = detalle.HasValue ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(int));
    
            var autorizantesParameter = autorizantes != null ?
                new ObjectParameter("Autorizantes", autorizantes) :
                new ObjectParameter("Autorizantes", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatSolicitudesSu", folioSolicitudParameter, fecha_SolicitudParameter, perfil_IdentParameter, solicitante_IdentParameter, solicintante_NombreParameter, puesto_solicitante_IdentParameter, periodoNomina_IdParameter, periodoNominaOriginal_IdParameter, conceptoIdParameter, motivoIdParameter, justficacionParameter, responsable_IdParameter, detalleParameter, autorizantesParameter, estatus, userEmployeeIdParameter);
        }
    
        public virtual ObjectResult<RelPeriodicidadPaisCMB_Result> RelPeriodicidadPaisCMB(string country)
        {
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RelPeriodicidadPaisCMB_Result>("RelPeriodicidadPaisCMB", countryParameter);
        }
    
        public virtual ObjectResult<CatPerfilEmpleadosAccesosSel_Result> CatPerfilEmpleadosAccesosSel(Nullable<int> perfil_Ident)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPerfilEmpleadosAccesosSel_Result>("CatPerfilEmpleadosAccesosSel", perfil_IdentParameter);
        }
    
        public virtual int CatPerfilEmpleadosAccesosSi(Nullable<int> perfil_Ident, string selectedKeyNames, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            var selectedKeyNamesParameter = selectedKeyNames != null ?
                new ObjectParameter("SelectedKeyNames", selectedKeyNames) :
                new ObjectParameter("SelectedKeyNames", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPerfilEmpleadosAccesosSi", perfil_IdentParameter, selectedKeyNamesParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual int CatPerfilEmpleadosAccesosSu(Nullable<int> perfil_Ident, Nullable<int> empleadoId, Nullable<int> userEmployeeId, Nullable<bool> active, ObjectParameter estatus)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            var empleadoIdParameter = empleadoId.HasValue ?
                new ObjectParameter("EmpleadoId", empleadoId) :
                new ObjectParameter("EmpleadoId", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPerfilEmpleadosAccesosSu", perfil_IdentParameter, empleadoIdParameter, userEmployeeIdParameter, activeParameter, estatus);
        }
    
        public virtual int CatSolicitudesSi(Nullable<int> folioSolicitud, string fecha_Solicitud, Nullable<int> perfil_Ident, Nullable<int> solicitante_Ident, string solicintante_Nombre, Nullable<int> puesto_solicitante_Ident, string periodoNomina_Id, Nullable<int> conceptoId, Nullable<int> motivoId, string justficacion, Nullable<int> responsable_Id, Nullable<int> detalle, string periodoNominaOriginal_Id, string autorizantes, string listaEmpleados, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var folioSolicitudParameter = folioSolicitud.HasValue ?
                new ObjectParameter("FolioSolicitud", folioSolicitud) :
                new ObjectParameter("FolioSolicitud", typeof(int));
    
            var fecha_SolicitudParameter = fecha_Solicitud != null ?
                new ObjectParameter("Fecha_Solicitud", fecha_Solicitud) :
                new ObjectParameter("Fecha_Solicitud", typeof(string));
    
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            var solicitante_IdentParameter = solicitante_Ident.HasValue ?
                new ObjectParameter("Solicitante_Ident", solicitante_Ident) :
                new ObjectParameter("Solicitante_Ident", typeof(int));
    
            var solicintante_NombreParameter = solicintante_Nombre != null ?
                new ObjectParameter("Solicintante_Nombre", solicintante_Nombre) :
                new ObjectParameter("Solicintante_Nombre", typeof(string));
    
            var puesto_solicitante_IdentParameter = puesto_solicitante_Ident.HasValue ?
                new ObjectParameter("Puesto_solicitante_Ident", puesto_solicitante_Ident) :
                new ObjectParameter("Puesto_solicitante_Ident", typeof(int));
    
            var periodoNomina_IdParameter = periodoNomina_Id != null ?
                new ObjectParameter("PeriodoNomina_Id", periodoNomina_Id) :
                new ObjectParameter("PeriodoNomina_Id", typeof(string));
    
            var conceptoIdParameter = conceptoId.HasValue ?
                new ObjectParameter("ConceptoId", conceptoId) :
                new ObjectParameter("ConceptoId", typeof(int));
    
            var motivoIdParameter = motivoId.HasValue ?
                new ObjectParameter("MotivoId", motivoId) :
                new ObjectParameter("MotivoId", typeof(int));
    
            var justficacionParameter = justficacion != null ?
                new ObjectParameter("Justficacion", justficacion) :
                new ObjectParameter("Justficacion", typeof(string));
    
            var responsable_IdParameter = responsable_Id.HasValue ?
                new ObjectParameter("Responsable_Id", responsable_Id) :
                new ObjectParameter("Responsable_Id", typeof(int));
    
            var detalleParameter = detalle.HasValue ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(int));
    
            var periodoNominaOriginal_IdParameter = periodoNominaOriginal_Id != null ?
                new ObjectParameter("PeriodoNominaOriginal_Id", periodoNominaOriginal_Id) :
                new ObjectParameter("PeriodoNominaOriginal_Id", typeof(string));
    
            var autorizantesParameter = autorizantes != null ?
                new ObjectParameter("Autorizantes", autorizantes) :
                new ObjectParameter("Autorizantes", typeof(string));
    
            var listaEmpleadosParameter = listaEmpleados != null ?
                new ObjectParameter("ListaEmpleados", listaEmpleados) :
                new ObjectParameter("ListaEmpleados", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatSolicitudesSi", folioSolicitudParameter, fecha_SolicitudParameter, perfil_IdentParameter, solicitante_IdentParameter, solicintante_NombreParameter, puesto_solicitante_IdentParameter, periodoNomina_IdParameter, conceptoIdParameter, motivoIdParameter, justficacionParameter, responsable_IdParameter, detalleParameter, periodoNominaOriginal_IdParameter, autorizantesParameter, listaEmpleadosParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual ObjectResult<CatSolicitudesSel_Result> CatSolicitudesSel(Nullable<int> folioSolicitud)
        {
            var folioSolicitudParameter = folioSolicitud.HasValue ?
                new ObjectParameter("FolioSolicitud", folioSolicitud) :
                new ObjectParameter("FolioSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatSolicitudesSel_Result>("CatSolicitudesSel", folioSolicitudParameter);
        }
    
        public virtual ObjectResult<CatEmpleadosSolicitudesSel_Result> CatEmpleadosSolicitudesSel(Nullable<int> folioSolicitud)
        {
            var folioSolicitudParameter = folioSolicitud.HasValue ?
                new ObjectParameter("FolioSolicitud", folioSolicitud) :
                new ObjectParameter("FolioSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmpleadosSolicitudesSel_Result>("CatEmpleadosSolicitudesSel", folioSolicitudParameter);
        }
    
        public virtual int CatEmpleadosSolicitudesSi(Nullable<int> folioSolicitud, Nullable<int> empleado_Ident, string empleado_First_Name, string empleado_Middle_Name, string empleado_Last_Name, Nullable<int> empleado_Position_Code_Ident, string empleado_Position_Code_Title, Nullable<int> empleado_Contract_Type_Ident, string empleado_Contract_Type, Nullable<int> manager_Ident, string manager_First_Name, string manager_Middle_Name, string manager_Last_Name, Nullable<int> manager_Position_Code_Ident, string manager_Position_Code_Title, Nullable<int> manager_Contract_Type_Ident, string manager_Contract_Type, Nullable<decimal> parametroConceptoMonto, string detalle, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var folioSolicitudParameter = folioSolicitud.HasValue ?
                new ObjectParameter("FolioSolicitud", folioSolicitud) :
                new ObjectParameter("FolioSolicitud", typeof(int));
    
            var empleado_IdentParameter = empleado_Ident.HasValue ?
                new ObjectParameter("Empleado_Ident", empleado_Ident) :
                new ObjectParameter("Empleado_Ident", typeof(int));
    
            var empleado_First_NameParameter = empleado_First_Name != null ?
                new ObjectParameter("Empleado_First_Name", empleado_First_Name) :
                new ObjectParameter("Empleado_First_Name", typeof(string));
    
            var empleado_Middle_NameParameter = empleado_Middle_Name != null ?
                new ObjectParameter("Empleado_Middle_Name", empleado_Middle_Name) :
                new ObjectParameter("Empleado_Middle_Name", typeof(string));
    
            var empleado_Last_NameParameter = empleado_Last_Name != null ?
                new ObjectParameter("Empleado_Last_Name", empleado_Last_Name) :
                new ObjectParameter("Empleado_Last_Name", typeof(string));
    
            var empleado_Position_Code_IdentParameter = empleado_Position_Code_Ident.HasValue ?
                new ObjectParameter("Empleado_Position_Code_Ident", empleado_Position_Code_Ident) :
                new ObjectParameter("Empleado_Position_Code_Ident", typeof(int));
    
            var empleado_Position_Code_TitleParameter = empleado_Position_Code_Title != null ?
                new ObjectParameter("Empleado_Position_Code_Title", empleado_Position_Code_Title) :
                new ObjectParameter("Empleado_Position_Code_Title", typeof(string));
    
            var empleado_Contract_Type_IdentParameter = empleado_Contract_Type_Ident.HasValue ?
                new ObjectParameter("Empleado_Contract_Type_Ident", empleado_Contract_Type_Ident) :
                new ObjectParameter("Empleado_Contract_Type_Ident", typeof(int));
    
            var empleado_Contract_TypeParameter = empleado_Contract_Type != null ?
                new ObjectParameter("Empleado_Contract_Type", empleado_Contract_Type) :
                new ObjectParameter("Empleado_Contract_Type", typeof(string));
    
            var manager_IdentParameter = manager_Ident.HasValue ?
                new ObjectParameter("Manager_Ident", manager_Ident) :
                new ObjectParameter("Manager_Ident", typeof(int));
    
            var manager_First_NameParameter = manager_First_Name != null ?
                new ObjectParameter("Manager_First_Name", manager_First_Name) :
                new ObjectParameter("Manager_First_Name", typeof(string));
    
            var manager_Middle_NameParameter = manager_Middle_Name != null ?
                new ObjectParameter("Manager_Middle_Name", manager_Middle_Name) :
                new ObjectParameter("Manager_Middle_Name", typeof(string));
    
            var manager_Last_NameParameter = manager_Last_Name != null ?
                new ObjectParameter("Manager_Last_Name", manager_Last_Name) :
                new ObjectParameter("Manager_Last_Name", typeof(string));
    
            var manager_Position_Code_IdentParameter = manager_Position_Code_Ident.HasValue ?
                new ObjectParameter("Manager_Position_Code_Ident", manager_Position_Code_Ident) :
                new ObjectParameter("Manager_Position_Code_Ident", typeof(int));
    
            var manager_Position_Code_TitleParameter = manager_Position_Code_Title != null ?
                new ObjectParameter("Manager_Position_Code_Title", manager_Position_Code_Title) :
                new ObjectParameter("Manager_Position_Code_Title", typeof(string));
    
            var manager_Contract_Type_IdentParameter = manager_Contract_Type_Ident.HasValue ?
                new ObjectParameter("Manager_Contract_Type_Ident", manager_Contract_Type_Ident) :
                new ObjectParameter("Manager_Contract_Type_Ident", typeof(int));
    
            var manager_Contract_TypeParameter = manager_Contract_Type != null ?
                new ObjectParameter("Manager_Contract_Type", manager_Contract_Type) :
                new ObjectParameter("Manager_Contract_Type", typeof(string));
    
            var parametroConceptoMontoParameter = parametroConceptoMonto.HasValue ?
                new ObjectParameter("ParametroConceptoMonto", parametroConceptoMonto) :
                new ObjectParameter("ParametroConceptoMonto", typeof(decimal));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatEmpleadosSolicitudesSi", folioSolicitudParameter, empleado_IdentParameter, empleado_First_NameParameter, empleado_Middle_NameParameter, empleado_Last_NameParameter, empleado_Position_Code_IdentParameter, empleado_Position_Code_TitleParameter, empleado_Contract_Type_IdentParameter, empleado_Contract_TypeParameter, manager_IdentParameter, manager_First_NameParameter, manager_Middle_NameParameter, manager_Last_NameParameter, manager_Position_Code_IdentParameter, manager_Position_Code_TitleParameter, manager_Contract_Type_IdentParameter, manager_Contract_TypeParameter, parametroConceptoMontoParameter, detalleParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatEmpleadosSolicitudesSu(Nullable<int> folioSolicitud, Nullable<int> empleado_Ident, Nullable<decimal> parametroConceptoMonto, string detalle, Nullable<bool> active, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var folioSolicitudParameter = folioSolicitud.HasValue ?
                new ObjectParameter("FolioSolicitud", folioSolicitud) :
                new ObjectParameter("FolioSolicitud", typeof(int));
    
            var empleado_IdentParameter = empleado_Ident.HasValue ?
                new ObjectParameter("Empleado_Ident", empleado_Ident) :
                new ObjectParameter("Empleado_Ident", typeof(int));
    
            var parametroConceptoMontoParameter = parametroConceptoMonto.HasValue ?
                new ObjectParameter("ParametroConceptoMonto", parametroConceptoMonto) :
                new ObjectParameter("ParametroConceptoMonto", typeof(decimal));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatEmpleadosSolicitudesSu", folioSolicitudParameter, empleado_IdentParameter, parametroConceptoMontoParameter, detalleParameter, activeParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual ObjectResult<CatEmployeeCMB_Result> CatEmployeeCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeCMB_Result>("CatEmployeeCMB");
        }
    
        public virtual ObjectResult<CatEmpleadosPerfilEmpleadosCMB_Result> CatEmpleadosPerfilEmpleadosCMB(Nullable<int> perfil_Ident)
        {
            var perfil_IdentParameter = perfil_Ident.HasValue ?
                new ObjectParameter("Perfil_Ident", perfil_Ident) :
                new ObjectParameter("Perfil_Ident", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmpleadosPerfilEmpleadosCMB_Result>("CatEmpleadosPerfilEmpleadosCMB", perfil_IdentParameter);
        }
    
        public virtual int CatSolicitudEmpleadosDetalleSu(Nullable<int> solicitudId, Nullable<int> catEmpleadoId, string catConceptoMotivoId, Nullable<int> responsableId, string periodoNomina, Nullable<bool> active, Nullable<bool> tTConceptoMotivoId, Nullable<bool> tTManager_Ident, Nullable<bool> tTMonto, Nullable<bool> tTDetalle, Nullable<bool> tTPeriodoNomina, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var solicitudIdParameter = solicitudId.HasValue ?
                new ObjectParameter("SolicitudId", solicitudId) :
                new ObjectParameter("SolicitudId", typeof(int));
    
            var catEmpleadoIdParameter = catEmpleadoId.HasValue ?
                new ObjectParameter("CatEmpleadoId", catEmpleadoId) :
                new ObjectParameter("CatEmpleadoId", typeof(int));
    
            var catConceptoMotivoIdParameter = catConceptoMotivoId != null ?
                new ObjectParameter("CatConceptoMotivoId", catConceptoMotivoId) :
                new ObjectParameter("CatConceptoMotivoId", typeof(string));
    
            var responsableIdParameter = responsableId.HasValue ?
                new ObjectParameter("ResponsableId", responsableId) :
                new ObjectParameter("ResponsableId", typeof(int));
    
            var periodoNominaParameter = periodoNomina != null ?
                new ObjectParameter("PeriodoNomina", periodoNomina) :
                new ObjectParameter("PeriodoNomina", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var tTConceptoMotivoIdParameter = tTConceptoMotivoId.HasValue ?
                new ObjectParameter("TTConceptoMotivoId", tTConceptoMotivoId) :
                new ObjectParameter("TTConceptoMotivoId", typeof(bool));
    
            var tTManager_IdentParameter = tTManager_Ident.HasValue ?
                new ObjectParameter("TTManager_Ident", tTManager_Ident) :
                new ObjectParameter("TTManager_Ident", typeof(bool));
    
            var tTMontoParameter = tTMonto.HasValue ?
                new ObjectParameter("TTMonto", tTMonto) :
                new ObjectParameter("TTMonto", typeof(bool));
    
            var tTDetalleParameter = tTDetalle.HasValue ?
                new ObjectParameter("TTDetalle", tTDetalle) :
                new ObjectParameter("TTDetalle", typeof(bool));
    
            var tTPeriodoNominaParameter = tTPeriodoNomina.HasValue ?
                new ObjectParameter("TTPeriodoNomina", tTPeriodoNomina) :
                new ObjectParameter("TTPeriodoNomina", typeof(bool));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatSolicitudEmpleadosDetalleSu", solicitudIdParameter, catEmpleadoIdParameter, catConceptoMotivoIdParameter, responsableIdParameter, periodoNominaParameter, activeParameter, tTConceptoMotivoIdParameter, tTManager_IdentParameter, tTMontoParameter, tTDetalleParameter, tTPeriodoNominaParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int ProcesaSolicitudEmpleadoDetalleSi(Nullable<int> solicitudId, string listaEmpleados, Nullable<int> conceptoMotivoId, string listaConceptoMotivo, Nullable<bool> aplicaAtodos, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var solicitudIdParameter = solicitudId.HasValue ?
                new ObjectParameter("SolicitudId", solicitudId) :
                new ObjectParameter("SolicitudId", typeof(int));
    
            var listaEmpleadosParameter = listaEmpleados != null ?
                new ObjectParameter("ListaEmpleados", listaEmpleados) :
                new ObjectParameter("ListaEmpleados", typeof(string));
    
            var conceptoMotivoIdParameter = conceptoMotivoId.HasValue ?
                new ObjectParameter("ConceptoMotivoId", conceptoMotivoId) :
                new ObjectParameter("ConceptoMotivoId", typeof(int));
    
            var listaConceptoMotivoParameter = listaConceptoMotivo != null ?
                new ObjectParameter("ListaConceptoMotivo", listaConceptoMotivo) :
                new ObjectParameter("ListaConceptoMotivo", typeof(string));
    
            var aplicaAtodosParameter = aplicaAtodos.HasValue ?
                new ObjectParameter("AplicaAtodos", aplicaAtodos) :
                new ObjectParameter("AplicaAtodos", typeof(bool));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcesaSolicitudEmpleadoDetalleSi", solicitudIdParameter, listaEmpleadosParameter, conceptoMotivoIdParameter, listaConceptoMotivoParameter, aplicaAtodosParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatSolicitudEmpleadosDetalleSi(Nullable<int> solicitudId, Nullable<int> catEmpleadoId, Nullable<int> catConceptoMotivoId, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var solicitudIdParameter = solicitudId.HasValue ?
                new ObjectParameter("SolicitudId", solicitudId) :
                new ObjectParameter("SolicitudId", typeof(int));
    
            var catEmpleadoIdParameter = catEmpleadoId.HasValue ?
                new ObjectParameter("CatEmpleadoId", catEmpleadoId) :
                new ObjectParameter("CatEmpleadoId", typeof(int));
    
            var catConceptoMotivoIdParameter = catConceptoMotivoId.HasValue ?
                new ObjectParameter("CatConceptoMotivoId", catConceptoMotivoId) :
                new ObjectParameter("CatConceptoMotivoId", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatSolicitudEmpleadosDetalleSi", solicitudIdParameter, catEmpleadoIdParameter, catConceptoMotivoIdParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual ObjectResult<CatMotivoSolicitudCMB_Result> CatMotivoSolicitudCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMotivoSolicitudCMB_Result>("CatMotivoSolicitudCMB");
        }
    
        public virtual int CatSolicitudesArchivosSi(Nullable<int> folioSolicitud, string nombreArchivo, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var folioSolicitudParameter = folioSolicitud.HasValue ?
                new ObjectParameter("FolioSolicitud", folioSolicitud) :
                new ObjectParameter("FolioSolicitud", typeof(int));
    
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("NombreArchivo", nombreArchivo) :
                new ObjectParameter("NombreArchivo", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatSolicitudesArchivosSi", folioSolicitudParameter, nombreArchivoParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int CatSolicitudEmpleadosDetalleMasivoSi(Nullable<int> solicitudId, Nullable<int> catEmpleadoId, string detalle, Nullable<int> userEmployeeId, ObjectParameter estatus)
        {
            var solicitudIdParameter = solicitudId.HasValue ?
                new ObjectParameter("SolicitudId", solicitudId) :
                new ObjectParameter("SolicitudId", typeof(int));
    
            var catEmpleadoIdParameter = catEmpleadoId.HasValue ?
                new ObjectParameter("CatEmpleadoId", catEmpleadoId) :
                new ObjectParameter("CatEmpleadoId", typeof(int));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatSolicitudEmpleadosDetalleMasivoSi", solicitudIdParameter, catEmpleadoIdParameter, detalleParameter, userEmployeeIdParameter, estatus);
        }
    
        public virtual int ProcesaSolicitudEmpleados(Nullable<int> solicitudId, Nullable<int> empleado_Ident, string autorizantes, Nullable<int> userEmployeeId, string listaEmpleados, Nullable<decimal> parametroConceptoMonto, string detalle, ObjectParameter estatus)
        {
            var solicitudIdParameter = solicitudId.HasValue ?
                new ObjectParameter("SolicitudId", solicitudId) :
                new ObjectParameter("SolicitudId", typeof(int));
    
            var empleado_IdentParameter = empleado_Ident.HasValue ?
                new ObjectParameter("Empleado_Ident", empleado_Ident) :
                new ObjectParameter("Empleado_Ident", typeof(int));
    
            var autorizantesParameter = autorizantes != null ?
                new ObjectParameter("Autorizantes", autorizantes) :
                new ObjectParameter("Autorizantes", typeof(string));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var listaEmpleadosParameter = listaEmpleados != null ?
                new ObjectParameter("ListaEmpleados", listaEmpleados) :
                new ObjectParameter("ListaEmpleados", typeof(string));
    
            var parametroConceptoMontoParameter = parametroConceptoMonto.HasValue ?
                new ObjectParameter("ParametroConceptoMonto", parametroConceptoMonto) :
                new ObjectParameter("ParametroConceptoMonto", typeof(decimal));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcesaSolicitudEmpleados", solicitudIdParameter, empleado_IdentParameter, autorizantesParameter, userEmployeeIdParameter, listaEmpleadosParameter, parametroConceptoMontoParameter, detalleParameter, estatus);
        }
    }
}
