//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatLogError
    {
        public int LogErrorId { get; set; }
        public string LogErrorMessage { get; set; }
        public string StackTrace { get; set; }
        public string Browser { get; set; }
        public string IpAddress { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedFromPCName { get; set; }
    }
}
