//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CatRole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CatRole()
    {
        this.RelUserRole = new HashSet<RelUserRole>();
    }

    public int CatRoleId { get; set; }
    public string Role { get; set; }
    public bool Active { get; set; }
    public int CreatedBy { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public Nullable<System.DateTime> DeactivatedDate { get; set; }
    public Nullable<int> DeactivatedBy { get; set; }
    public int LastModifiedBy { get; set; }
    public System.DateTime LastModifiedDate { get; set; }
    public string LastModifiedFromPCName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RelUserRole> RelUserRole { get; set; }
}
