//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InformationSecurityEntities : DbContext
    {
        public InformationSecurityEntities()
            : base("name=InformationSecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RelRoleClient> RelRoleClient { get; set; }
        public virtual DbSet<TraClericalImages> TraClericalImages { get; set; }
    
        public virtual int AllAccountsByManagerIdSel(Nullable<int> managerId)
        {
            var managerIdParameter = managerId.HasValue ?
                new ObjectParameter("ManagerId", managerId) :
                new ObjectParameter("ManagerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AllAccountsByManagerIdSel", managerIdParameter);
        }
    
        public virtual int CargaInicialNewGAPP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CargaInicialNewGAPP");
        }
    
        public virtual ObjectResult<CatAccessLevelCMB_Result> CatAccessLevelCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAccessLevelCMB_Result>("CatAccessLevelCMB");
        }
    
        public virtual ObjectResult<CatAccountIdByManagerIdSel_Result> CatAccountIdByManagerIdSel(Nullable<int> managerId, Nullable<int> cCMSIDUser)
        {
            var managerIdParameter = managerId.HasValue ?
                new ObjectParameter("ManagerId", managerId) :
                new ObjectParameter("ManagerId", typeof(int));
    
            var cCMSIDUserParameter = cCMSIDUser.HasValue ?
                new ObjectParameter("CCMSIDUser", cCMSIDUser) :
                new ObjectParameter("CCMSIDUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAccountIdByManagerIdSel_Result>("CatAccountIdByManagerIdSel", managerIdParameter, cCMSIDUserParameter);
        }
    
        public virtual ObjectResult<CatActionByAccessCardSel_Result> CatActionByAccessCardSel(Nullable<int> catActionId, Nullable<int> cCMSID)
        {
            var catActionIdParameter = catActionId.HasValue ?
                new ObjectParameter("CatActionId", catActionId) :
                new ObjectParameter("CatActionId", typeof(int));
    
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatActionByAccessCardSel_Result>("CatActionByAccessCardSel", catActionIdParameter, cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatActionCMB_Result> CatActionCMB(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatActionCMB_Result>("CatActionCMB", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatActionGRIDCMB_Result> CatActionGRIDCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatActionGRIDCMB_Result>("CatActionGRIDCMB");
        }
    
        public virtual ObjectResult<CatAllActionCMB_Result> CatAllActionCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatAllActionCMB_Result>("CatAllActionCMB");
        }
    
        public virtual ObjectResult<CatBadgeIn24AgentsClassCMB_Result> CatBadgeIn24AgentsClassCMB(Nullable<int> locid)
        {
            var locidParameter = locid.HasValue ?
                new ObjectParameter("Locid", locid) :
                new ObjectParameter("Locid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatBadgeIn24AgentsClassCMB_Result>("CatBadgeIn24AgentsClassCMB", locidParameter);
        }
    
        public virtual ObjectResult<CatBadgeIn24AgentsEmployeeSel_Result> CatBadgeIn24AgentsEmployeeSel(Nullable<int> useremployee, Nullable<int> classIdent)
        {
            var useremployeeParameter = useremployee.HasValue ?
                new ObjectParameter("Useremployee", useremployee) :
                new ObjectParameter("Useremployee", typeof(int));
    
            var classIdentParameter = classIdent.HasValue ?
                new ObjectParameter("ClassIdent", classIdent) :
                new ObjectParameter("ClassIdent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatBadgeIn24AgentsEmployeeSel_Result>("CatBadgeIn24AgentsEmployeeSel", useremployeeParameter, classIdentParameter);
        }
    
        public virtual ObjectResult<CatBadgeIn24AgentsSel_Result> CatBadgeIn24AgentsSel(Nullable<int> eID)
        {
            var eIDParameter = eID.HasValue ?
                new ObjectParameter("EID", eID) :
                new ObjectParameter("EID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatBadgeIn24AgentsSel_Result>("CatBadgeIn24AgentsSel", eIDParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatBadgeIn24AgentsSi(Nullable<int> userEmployeeId, Nullable<int> employeeId, Nullable<int> badgeNumber, Nullable<int> classIdent)
        {
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var badgeNumberParameter = badgeNumber.HasValue ?
                new ObjectParameter("BadgeNumber", badgeNumber) :
                new ObjectParameter("BadgeNumber", typeof(int));
    
            var classIdentParameter = classIdent.HasValue ?
                new ObjectParameter("ClassIdent", classIdent) :
                new ObjectParameter("ClassIdent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatBadgeIn24AgentsSi", userEmployeeIdParameter, employeeIdParameter, badgeNumberParameter, classIdentParameter);
        }
    
        public virtual int CatBadgeIn24AgentsSu(Nullable<int> userEmployeeId, Nullable<int> employeeId, Nullable<int> badgeNumber, Nullable<int> catBadgeIn24Id)
        {
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var badgeNumberParameter = badgeNumber.HasValue ?
                new ObjectParameter("BadgeNumber", badgeNumber) :
                new ObjectParameter("BadgeNumber", typeof(int));
    
            var catBadgeIn24IdParameter = catBadgeIn24Id.HasValue ?
                new ObjectParameter("CatBadgeIn24Id", catBadgeIn24Id) :
                new ObjectParameter("CatBadgeIn24Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatBadgeIn24AgentsSu", userEmployeeIdParameter, employeeIdParameter, badgeNumberParameter, catBadgeIn24IdParameter);
        }
    
        public virtual ObjectResult<CatBadgeIn24Sel_Result> CatBadgeIn24Sel(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatBadgeIn24Sel_Result>("CatBadgeIn24Sel", employeeIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatBadgeIn24Si(Nullable<int> userEmployeeId, Nullable<int> employeeId, Nullable<int> badgeNumber)
        {
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var badgeNumberParameter = badgeNumber.HasValue ?
                new ObjectParameter("BadgeNumber", badgeNumber) :
                new ObjectParameter("BadgeNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatBadgeIn24Si", userEmployeeIdParameter, employeeIdParameter, badgeNumberParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatBadgeIn24Su(Nullable<int> userEmployeeId, Nullable<int> employeeId, string dateCommitted)
        {
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var dateCommittedParameter = dateCommitted != null ?
                new ObjectParameter("DateCommitted", dateCommitted) :
                new ObjectParameter("DateCommitted", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatBadgeIn24Su", userEmployeeIdParameter, employeeIdParameter, dateCommittedParameter);
        }
    
        public virtual ObjectResult<CatBadgeIn24ValidateSel_Result> CatBadgeIn24ValidateSel(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatBadgeIn24ValidateSel_Result>("CatBadgeIn24ValidateSel", employeeIdParameter);
        }
    
        public virtual ObjectResult<CatCardRangeSel_Result> CatCardRangeSel(Nullable<int> countryId, Nullable<int> isAdmin)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCardRangeSel_Result>("CatCardRangeSel", countryIdParameter, isAdminParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatCardRangeSi(Nullable<long> rangeIni, Nullable<long> rangeEnd, Nullable<int> userEmployeeId, Nullable<int> countryId)
        {
            var rangeIniParameter = rangeIni.HasValue ?
                new ObjectParameter("RangeIni", rangeIni) :
                new ObjectParameter("RangeIni", typeof(long));
    
            var rangeEndParameter = rangeEnd.HasValue ?
                new ObjectParameter("RangeEnd", rangeEnd) :
                new ObjectParameter("RangeEnd", typeof(long));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatCardRangeSi", rangeIniParameter, rangeEndParameter, userEmployeeIdParameter, countryIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatCardRangeSu(Nullable<long> rangeIni, Nullable<long> rangeEnd, Nullable<int> userEmployeeId, Nullable<int> cardRangeId)
        {
            var rangeIniParameter = rangeIni.HasValue ?
                new ObjectParameter("RangeIni", rangeIni) :
                new ObjectParameter("RangeIni", typeof(long));
    
            var rangeEndParameter = rangeEnd.HasValue ?
                new ObjectParameter("RangeEnd", rangeEnd) :
                new ObjectParameter("RangeEnd", typeof(long));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var cardRangeIdParameter = cardRangeId.HasValue ?
                new ObjectParameter("CardRangeId", cardRangeId) :
                new ObjectParameter("CardRangeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatCardRangeSu", rangeIniParameter, rangeEndParameter, userEmployeeIdParameter, cardRangeIdParameter);
        }
    
        public virtual ObjectResult<CatClientByLocationCMB_Result> CatClientByLocationCMB(Nullable<int> locId)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClientByLocationCMB_Result>("CatClientByLocationCMB", locIdParameter);
        }
    
        public virtual ObjectResult<CatClientCCMSCMB_Result> CatClientCCMSCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClientCCMSCMB_Result>("CatClientCCMSCMB");
        }
    
        public virtual ObjectResult<CatClientsClericalCMB_Result> CatClientsClericalCMB(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClientsClericalCMB_Result>("CatClientsClericalCMB", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatCountryCMB_Result> CatCountryCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatCountryCMB_Result>("CatCountryCMB");
        }
    
        public virtual ObjectResult<CatDaysYearR2OPSCMB_Result> CatDaysYearR2OPSCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatDaysYearR2OPSCMB_Result>("CatDaysYearR2OPSCMB");
        }
    
        public virtual ObjectResult<CatEmailBySiteSel_Result> CatEmailBySiteSel(Nullable<int> locId)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmailBySiteSel_Result>("CatEmailBySiteSel", locIdParameter);
        }
    
        public virtual ObjectResult<CatEmployeeActiveCMB_Result> CatEmployeeActiveCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeActiveCMB_Result>("CatEmployeeActiveCMB");
        }
    
        public virtual ObjectResult<CatEmployeeCMB_Result> CatEmployeeCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeCMB_Result>("CatEmployeeCMB");
        }
    
        public virtual ObjectResult<CatEmployeeInfoRegistradoSel_Result> CatEmployeeInfoRegistradoSel(Nullable<int> ccmsid, Nullable<int> aPTerminationId)
        {
            var ccmsidParameter = ccmsid.HasValue ?
                new ObjectParameter("ccmsid", ccmsid) :
                new ObjectParameter("ccmsid", typeof(int));
    
            var aPTerminationIdParameter = aPTerminationId.HasValue ?
                new ObjectParameter("APTerminationId", aPTerminationId) :
                new ObjectParameter("APTerminationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeInfoRegistradoSel_Result>("CatEmployeeInfoRegistradoSel", ccmsidParameter, aPTerminationIdParameter);
        }
    
        public virtual ObjectResult<CatEmployeeInfoSel_Result> CatEmployeeInfoSel(Nullable<int> ccmsid)
        {
            var ccmsidParameter = ccmsid.HasValue ?
                new ObjectParameter("ccmsid", ccmsid) :
                new ObjectParameter("ccmsid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeInfoSel_Result>("CatEmployeeInfoSel", ccmsidParameter);
        }
    
        public virtual ObjectResult<CatEmployeeManagerByEIdAPBajasSel_Result> CatEmployeeManagerByEIdAPBajasSel(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeManagerByEIdAPBajasSel_Result>("CatEmployeeManagerByEIdAPBajasSel", employeeIdParameter);
        }
    
        public virtual ObjectResult<CatEmployeeManagerByEIdSel_Result> CatEmployeeManagerByEIdSel(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeManagerByEIdSel_Result>("CatEmployeeManagerByEIdSel", employeeIdParameter);
        }
    
        public virtual ObjectResult<CatEmployeeRepositionSel_Result> CatEmployeeRepositionSel(Nullable<int> locId)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeeRepositionSel_Result>("CatEmployeeRepositionSel", locIdParameter);
        }
    
        public virtual ObjectResult<CatEmployeInfoValidationSel_Result> CatEmployeInfoValidationSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatEmployeInfoValidationSel_Result>("CatEmployeInfoValidationSel", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatLocationByEmployeeIdSel_Result> CatLocationByEmployeeIdSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatLocationByEmployeeIdSel_Result>("CatLocationByEmployeeIdSel", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatLocationCMB_Result> CatLocationCMB(Nullable<int> locId, Nullable<int> cCMSID)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatLocationCMB_Result>("CatLocationCMB", locIdParameter, cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatLocationEmployeeCMB_Result> CatLocationEmployeeCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatLocationEmployeeCMB_Result>("CatLocationEmployeeCMB");
        }
    
        public virtual ObjectResult<CatLocationEmployeeSel_Result> CatLocationEmployeeSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatLocationEmployeeSel_Result>("CatLocationEmployeeSel");
        }
    
        public virtual int CatLocationEmployeeSi(Nullable<int> cCMSID, Nullable<int> eID, Nullable<int> locId)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            var eIDParameter = eID.HasValue ?
                new ObjectParameter("EID", eID) :
                new ObjectParameter("EID", typeof(int));
    
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatLocationEmployeeSi", cCMSIDParameter, eIDParameter, locIdParameter);
        }
    
        public virtual int CatLocationEmployeeSu(Nullable<int> cCMSID, Nullable<int> catLocationEmployeeId, Nullable<int> eID, Nullable<int> locId, Nullable<bool> active)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            var catLocationEmployeeIdParameter = catLocationEmployeeId.HasValue ?
                new ObjectParameter("CatLocationEmployeeId", catLocationEmployeeId) :
                new ObjectParameter("CatLocationEmployeeId", typeof(int));
    
            var eIDParameter = eID.HasValue ?
                new ObjectParameter("EID", eID) :
                new ObjectParameter("EID", typeof(int));
    
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatLocationEmployeeSu", cCMSIDParameter, catLocationEmployeeIdParameter, eIDParameter, locIdParameter, activeParameter);
        }
    
        public virtual int CatLogErrorSi(string logErrorMessage, string stackTrace, string ipAddress, string browser, Nullable<int> createdBy)
        {
            var logErrorMessageParameter = logErrorMessage != null ?
                new ObjectParameter("LogErrorMessage", logErrorMessage) :
                new ObjectParameter("LogErrorMessage", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("IpAddress", ipAddress) :
                new ObjectParameter("IpAddress", typeof(string));
    
            var browserParameter = browser != null ?
                new ObjectParameter("Browser", browser) :
                new ObjectParameter("Browser", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatLogErrorSi", logErrorMessageParameter, stackTraceParameter, ipAddressParameter, browserParameter, createdByParameter);
        }
    
        public virtual ObjectResult<CatMotiveCMB_Result> CatMotiveCMB(Nullable<int> terminationTypeId)
        {
            var terminationTypeIdParameter = terminationTypeId.HasValue ?
                new ObjectParameter("TerminationTypeId", terminationTypeId) :
                new ObjectParameter("TerminationTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatMotiveCMB_Result>("CatMotiveCMB", terminationTypeIdParameter);
        }
    
        public virtual ObjectResult<CatNewHireEmployeeSel_Result> CatNewHireEmployeeSel(Nullable<int> locId, Nullable<int> cCMSID)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatNewHireEmployeeSel_Result>("CatNewHireEmployeeSel", locIdParameter, cCMSIDParameter);
        }
    
        public virtual int CatPoistionLevelDeactivateSu(Nullable<int> userEmployeeId, Nullable<int> cliId, Nullable<int> lvlId)
        {
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("CliId", cliId) :
                new ObjectParameter("CliId", typeof(int));
    
            var lvlIdParameter = lvlId.HasValue ?
                new ObjectParameter("LvlId", lvlId) :
                new ObjectParameter("LvlId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPoistionLevelDeactivateSu", userEmployeeIdParameter, cliIdParameter, lvlIdParameter);
        }
    
        public virtual ObjectResult<CatPositionCMB_Result> CatPositionCMB(Nullable<int> cliId, Nullable<int> lvlId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("CliId", cliId) :
                new ObjectParameter("CliId", typeof(int));
    
            var lvlIdParameter = lvlId.HasValue ?
                new ObjectParameter("LvlId", lvlId) :
                new ObjectParameter("LvlId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPositionCMB_Result>("CatPositionCMB", cliIdParameter, lvlIdParameter);
        }
    
        public virtual int CatPositionLevelDeactivateByIdSu(Nullable<int> posId, Nullable<int> userEmployeeId)
        {
            var posIdParameter = posId.HasValue ?
                new ObjectParameter("PosId", posId) :
                new ObjectParameter("PosId", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatPositionLevelDeactivateByIdSu", posIdParameter, userEmployeeIdParameter);
        }
    
        public virtual ObjectResult<CatPositionLevelSel_Result> CatPositionLevelSel(Nullable<int> cliId, Nullable<int> lvlId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("CliId", cliId) :
                new ObjectParameter("CliId", typeof(int));
    
            var lvlIdParameter = lvlId.HasValue ?
                new ObjectParameter("LvlId", lvlId) :
                new ObjectParameter("LvlId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatPositionLevelSel_Result>("CatPositionLevelSel", cliIdParameter, lvlIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatPositionLevelSi(Nullable<int> userEmployeeId, Nullable<int> posId, Nullable<int> cliId, Nullable<int> lvlId, Nullable<bool> active)
        {
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var posIdParameter = posId.HasValue ?
                new ObjectParameter("PosId", posId) :
                new ObjectParameter("PosId", typeof(int));
    
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("CliId", cliId) :
                new ObjectParameter("CliId", typeof(int));
    
            var lvlIdParameter = lvlId.HasValue ?
                new ObjectParameter("LvlId", lvlId) :
                new ObjectParameter("LvlId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatPositionLevelSi", userEmployeeIdParameter, posIdParameter, cliIdParameter, lvlIdParameter, activeParameter);
        }
    
        public virtual int CatProDeproLogSi(Nullable<int> catProDeproId)
        {
            var catProDeproIdParameter = catProDeproId.HasValue ?
                new ObjectParameter("CatProDeproId", catProDeproId) :
                new ObjectParameter("CatProDeproId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatProDeproLogSi", catProDeproIdParameter);
        }
    
        public virtual int CatProDeproSd(Nullable<int> catProDeproId)
        {
            var catProDeproIdParameter = catProDeproId.HasValue ?
                new ObjectParameter("CatProDeproId", catProDeproId) :
                new ObjectParameter("CatProDeproId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatProDeproSd", catProDeproIdParameter);
        }
    
        public virtual ObjectResult<CatProDeproSel_Result> CatProDeproSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatProDeproSel_Result>("CatProDeproSel", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatProDeproSi_Result> CatProDeproSi(Nullable<int> cCMSIDUser, Nullable<int> cCMSID, Nullable<int> actionId, Nullable<int> subAction, string fechaIni, string fechaFin)
        {
            var cCMSIDUserParameter = cCMSIDUser.HasValue ?
                new ObjectParameter("CCMSIDUser", cCMSIDUser) :
                new ObjectParameter("CCMSIDUser", typeof(int));
    
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            var subActionParameter = subAction.HasValue ?
                new ObjectParameter("SubAction", subAction) :
                new ObjectParameter("SubAction", typeof(int));
    
            var fechaIniParameter = fechaIni != null ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatProDeproSi_Result>("CatProDeproSi", cCMSIDUserParameter, cCMSIDParameter, actionIdParameter, subActionParameter, fechaIniParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<CatProgramByClientIdCMB_Result> CatProgramByClientIdCMB(Nullable<int> clientId, Nullable<int> locId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("locId", locId) :
                new ObjectParameter("locId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatProgramByClientIdCMB_Result>("CatProgramByClientIdCMB", clientIdParameter, locIdParameter);
        }
    
        public virtual ObjectResult<CatProgramClientLocationVwCMB_Result> CatProgramClientLocationVwCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatProgramClientLocationVwCMB_Result>("CatProgramClientLocationVwCMB");
        }
    
        public virtual ObjectResult<CatRelUserRoleSel_Result> CatRelUserRoleSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatRelUserRoleSel_Result>("CatRelUserRoleSel", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatReportClericalSel_Result> CatReportClericalSel(string fechonaIni, string fechonaFin, Nullable<int> clientId, Nullable<int> ccmsId)
        {
            var fechonaIniParameter = fechonaIni != null ?
                new ObjectParameter("fechonaIni", fechonaIni) :
                new ObjectParameter("fechonaIni", typeof(string));
    
            var fechonaFinParameter = fechonaFin != null ?
                new ObjectParameter("fechonaFin", fechonaFin) :
                new ObjectParameter("fechonaFin", typeof(string));
    
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("clientId", clientId) :
                new ObjectParameter("clientId", typeof(int));
    
            var ccmsIdParameter = ccmsId.HasValue ?
                new ObjectParameter("ccmsId", ccmsId) :
                new ObjectParameter("ccmsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatReportClericalSel_Result>("CatReportClericalSel", fechonaIniParameter, fechonaFinParameter, clientIdParameter, ccmsIdParameter);
        }
    
        public virtual ObjectResult<CatReportSel_Result> CatReportSel(string fechonaIni, string fechonaFin, Nullable<int> location, Nullable<int> client, Nullable<int> program, Nullable<int> employ, Nullable<int> action, Nullable<int> userCCMSID)
        {
            var fechonaIniParameter = fechonaIni != null ?
                new ObjectParameter("fechonaIni", fechonaIni) :
                new ObjectParameter("fechonaIni", typeof(string));
    
            var fechonaFinParameter = fechonaFin != null ?
                new ObjectParameter("fechonaFin", fechonaFin) :
                new ObjectParameter("fechonaFin", typeof(string));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            var clientParameter = client.HasValue ?
                new ObjectParameter("client", client) :
                new ObjectParameter("client", typeof(int));
    
            var programParameter = program.HasValue ?
                new ObjectParameter("program", program) :
                new ObjectParameter("program", typeof(int));
    
            var employParameter = employ.HasValue ?
                new ObjectParameter("employ", employ) :
                new ObjectParameter("employ", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            var userCCMSIDParameter = userCCMSID.HasValue ?
                new ObjectParameter("UserCCMSID", userCCMSID) :
                new ObjectParameter("UserCCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatReportSel_Result>("CatReportSel", fechonaIniParameter, fechonaFinParameter, locationParameter, clientParameter, programParameter, employParameter, actionParameter, userCCMSIDParameter);
        }
    
        public virtual ObjectResult<CatRepositionNumberCMB_Result> CatRepositionNumberCMB(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatRepositionNumberCMB_Result>("CatRepositionNumberCMB", cCMSIDParameter);
        }
    
        public virtual ObjectResult<CatRepositionNumberSel_Result> CatRepositionNumberSel(Nullable<int> countryId, Nullable<int> isAdmin)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatRepositionNumberSel_Result>("CatRepositionNumberSel", countryIdParameter, isAdminParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatRepositionNumberSi(Nullable<long> badgenumber, Nullable<int> accessLevelId, Nullable<int> clientId, Nullable<int> userEmployeeId, Nullable<int> countryId)
        {
            var badgenumberParameter = badgenumber.HasValue ?
                new ObjectParameter("Badgenumber", badgenumber) :
                new ObjectParameter("Badgenumber", typeof(long));
    
            var accessLevelIdParameter = accessLevelId.HasValue ?
                new ObjectParameter("AccessLevelId", accessLevelId) :
                new ObjectParameter("AccessLevelId", typeof(int));
    
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatRepositionNumberSi", badgenumberParameter, accessLevelIdParameter, clientIdParameter, userEmployeeIdParameter, countryIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> CatRepositionNumberSu(Nullable<long> badgenumber, Nullable<int> accessLevelId, Nullable<int> clientId, Nullable<int> userEmployeeId, Nullable<int> countryId, Nullable<int> repositionNumberId)
        {
            var badgenumberParameter = badgenumber.HasValue ?
                new ObjectParameter("Badgenumber", badgenumber) :
                new ObjectParameter("Badgenumber", typeof(long));
    
            var accessLevelIdParameter = accessLevelId.HasValue ?
                new ObjectParameter("AccessLevelId", accessLevelId) :
                new ObjectParameter("AccessLevelId", typeof(int));
    
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            var repositionNumberIdParameter = repositionNumberId.HasValue ?
                new ObjectParameter("RepositionNumberId", repositionNumberId) :
                new ObjectParameter("RepositionNumberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("CatRepositionNumberSu", badgenumberParameter, accessLevelIdParameter, clientIdParameter, userEmployeeIdParameter, countryIdParameter, repositionNumberIdParameter);
        }
    
        public virtual ObjectResult<CatRoleCMB_Result> CatRoleCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatRoleCMB_Result>("CatRoleCMB");
        }
    
        public virtual ObjectResult<CatScheduleEmployeeCMB_Result> CatScheduleEmployeeCMB(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatScheduleEmployeeCMB_Result>("CatScheduleEmployeeCMB", cCMSIDParameter);
        }
    
        public virtual ObjectResult<string> CatServerConfigADByIdSel(Nullable<int> domainId)
        {
            var domainIdParameter = domainId.HasValue ?
                new ObjectParameter("DomainId", domainId) :
                new ObjectParameter("DomainId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CatServerConfigADByIdSel", domainIdParameter);
        }
    
        public virtual ObjectResult<CatServerConfigADCmb_Result> CatServerConfigADCmb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatServerConfigADCmb_Result>("CatServerConfigADCmb");
        }
    
        public virtual int CatServerConfigADSI(string serverConfigADName, string serverConfigADPath, Nullable<int> createdBy)
        {
            var serverConfigADNameParameter = serverConfigADName != null ?
                new ObjectParameter("ServerConfigADName", serverConfigADName) :
                new ObjectParameter("ServerConfigADName", typeof(string));
    
            var serverConfigADPathParameter = serverConfigADPath != null ?
                new ObjectParameter("ServerConfigADPath", serverConfigADPath) :
                new ObjectParameter("ServerConfigADPath", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatServerConfigADSI", serverConfigADNameParameter, serverConfigADPathParameter, createdByParameter);
        }
    
        public virtual ObjectResult<CatServerConfigLocationADSel_Result> CatServerConfigLocationADSel(string accountId)
        {
            var accountIdParameter = accountId != null ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatServerConfigLocationADSel_Result>("CatServerConfigLocationADSel", accountIdParameter);
        }
    
        public virtual ObjectResult<CatSubActionCMB_Result> CatSubActionCMB(Nullable<int> accionId)
        {
            var accionIdParameter = accionId.HasValue ?
                new ObjectParameter("AccionId", accionId) :
                new ObjectParameter("AccionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatSubActionCMB_Result>("CatSubActionCMB", accionIdParameter);
        }
    
        public virtual ObjectResult<CatSubActionGRIDCMB_Result> CatSubActionGRIDCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatSubActionGRIDCMB_Result>("CatSubActionGRIDCMB");
        }
    
        public virtual int CatTempoTarjetasSi(string cCMSID, string firstName, string surname, Nullable<int> cardId, Nullable<int> cardNumber, Nullable<int> accessLevel, Nullable<int> cardStatus)
        {
            var cCMSIDParameter = cCMSID != null ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var cardIdParameter = cardId.HasValue ?
                new ObjectParameter("CardId", cardId) :
                new ObjectParameter("CardId", typeof(int));
    
            var cardNumberParameter = cardNumber.HasValue ?
                new ObjectParameter("CardNumber", cardNumber) :
                new ObjectParameter("CardNumber", typeof(int));
    
            var accessLevelParameter = accessLevel.HasValue ?
                new ObjectParameter("AccessLevel", accessLevel) :
                new ObjectParameter("AccessLevel", typeof(int));
    
            var cardStatusParameter = cardStatus.HasValue ?
                new ObjectParameter("CardStatus", cardStatus) :
                new ObjectParameter("CardStatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CatTempoTarjetasSi", cCMSIDParameter, firstNameParameter, surnameParameter, cardIdParameter, cardNumberParameter, accessLevelParameter, cardStatusParameter);
        }
    
        public virtual ObjectResult<CatTerminationTypeCMB_Result> CatTerminationTypeCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTerminationTypeCMB_Result>("CatTerminationTypeCMB");
        }
    
        public virtual ObjectResult<CatUserInfoSel_Result> CatUserInfoSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatUserInfoSel_Result>("CatUserInfoSel", cCMSIDParameter);
        }
    
        public virtual int EmailContentSel(Nullable<int> logActionId)
        {
            var logActionIdParameter = logActionId.HasValue ?
                new ObjectParameter("LogActionId", logActionId) :
                new ObjectParameter("LogActionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmailContentSel", logActionIdParameter);
        }
    
        public virtual int GetNewEmployeeBadgeNumberAutoSi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNewEmployeeBadgeNumberAutoSi");
        }
    
        public virtual ObjectResult<GetNewEmployeeBadgeNumberSel_Result> GetNewEmployeeBadgeNumberSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewEmployeeBadgeNumberSel_Result>("GetNewEmployeeBadgeNumberSel");
        }
    
        public virtual int LogActionsSI(string domain, string account, string actionDesc, Nullable<int> actionId, string ipAddressClient, Nullable<int> createdBy, ObjectParameter logActionsId)
        {
            var domainParameter = domain != null ?
                new ObjectParameter("Domain", domain) :
                new ObjectParameter("Domain", typeof(string));
    
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var actionDescParameter = actionDesc != null ?
                new ObjectParameter("ActionDesc", actionDesc) :
                new ObjectParameter("ActionDesc", typeof(string));
    
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            var ipAddressClientParameter = ipAddressClient != null ?
                new ObjectParameter("IpAddressClient", ipAddressClient) :
                new ObjectParameter("IpAddressClient", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogActionsSI", domainParameter, accountParameter, actionDescParameter, actionIdParameter, ipAddressClientParameter, createdByParameter, logActionsId);
        }
    
        public virtual int LogCatProDeproTerminationUserSi(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogCatProDeproTerminationUserSi", cCMSIDParameter);
        }
    
        public virtual int LogErrorSI(string logErrorMessage, string stackTrace, string ipAddress, string browser, Nullable<int> createdBy, ObjectParameter logErrorId)
        {
            var logErrorMessageParameter = logErrorMessage != null ?
                new ObjectParameter("LogErrorMessage", logErrorMessage) :
                new ObjectParameter("LogErrorMessage", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("IpAddress", ipAddress) :
                new ObjectParameter("IpAddress", typeof(string));
    
            var browserParameter = browser != null ?
                new ObjectParameter("Browser", browser) :
                new ObjectParameter("Browser", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogErrorSI", logErrorMessageParameter, stackTraceParameter, ipAddressParameter, browserParameter, createdByParameter, logErrorId);
        }
    
        public virtual ObjectResult<ManagersByHierarchySel_Result> ManagersByHierarchySel(Nullable<int> managerId)
        {
            var managerIdParameter = managerId.HasValue ?
                new ObjectParameter("ManagerId", managerId) :
                new ObjectParameter("ManagerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ManagersByHierarchySel_Result>("ManagersByHierarchySel", managerIdParameter);
        }
    
        public virtual ObjectResult<RelEmployeeAuthSel_Result> RelEmployeeAuthSel(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RelEmployeeAuthSel_Result>("RelEmployeeAuthSel", employeeIdParameter);
        }
    
        public virtual int RelEmployeeAuthSI(Nullable<int> employeeId, Nullable<bool> isAdmin, Nullable<int> lastModifiedBy)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            var lastModifiedByParameter = lastModifiedBy.HasValue ?
                new ObjectParameter("LastModifiedBy", lastModifiedBy) :
                new ObjectParameter("LastModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RelEmployeeAuthSI", employeeIdParameter, isAdminParameter, lastModifiedByParameter);
        }
    
        public virtual ObjectResult<RelPositionAuthSel_Result> RelPositionAuthSel(Nullable<int> positionId)
        {
            var positionIdParameter = positionId.HasValue ?
                new ObjectParameter("PositionId", positionId) :
                new ObjectParameter("PositionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RelPositionAuthSel_Result>("RelPositionAuthSel", positionIdParameter);
        }
    
        public virtual int RelPositionAuthSI(Nullable<int> positionId, Nullable<bool> isAdmin, Nullable<int> lastModifiedBy)
        {
            var positionIdParameter = positionId.HasValue ?
                new ObjectParameter("PositionId", positionId) :
                new ObjectParameter("PositionId", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            var lastModifiedByParameter = lastModifiedBy.HasValue ?
                new ObjectParameter("LastModifiedBy", lastModifiedBy) :
                new ObjectParameter("LastModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RelPositionAuthSI", positionIdParameter, isAdminParameter, lastModifiedByParameter);
        }
    
        public virtual ObjectResult<RelRoleClientSel_Result> RelRoleClientSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RelRoleClientSel_Result>("RelRoleClientSel");
        }
    
        public virtual int RelRoleClientSi(Nullable<int> modifiedByCCMSID, Nullable<int> clientId, Nullable<int> rolId)
        {
            var modifiedByCCMSIDParameter = modifiedByCCMSID.HasValue ?
                new ObjectParameter("ModifiedByCCMSID", modifiedByCCMSID) :
                new ObjectParameter("ModifiedByCCMSID", typeof(int));
    
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(int));
    
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RelRoleClientSi", modifiedByCCMSIDParameter, clientIdParameter, rolIdParameter);
        }
    
        public virtual int RelRoleClientSu(Nullable<int> modifiedByCCMSID, Nullable<int> relRoleClientId, Nullable<int> userCCMSID, Nullable<int> rolId, Nullable<bool> active)
        {
            var modifiedByCCMSIDParameter = modifiedByCCMSID.HasValue ?
                new ObjectParameter("ModifiedByCCMSID", modifiedByCCMSID) :
                new ObjectParameter("ModifiedByCCMSID", typeof(int));
    
            var relRoleClientIdParameter = relRoleClientId.HasValue ?
                new ObjectParameter("RelRoleClientId", relRoleClientId) :
                new ObjectParameter("RelRoleClientId", typeof(int));
    
            var userCCMSIDParameter = userCCMSID.HasValue ?
                new ObjectParameter("UserCCMSID", userCCMSID) :
                new ObjectParameter("UserCCMSID", typeof(int));
    
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RelRoleClientSu", modifiedByCCMSIDParameter, relRoleClientIdParameter, userCCMSIDParameter, rolIdParameter, activeParameter);
        }
    
        public virtual ObjectResult<RelUserRoleSel_Result> RelUserRoleSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RelUserRoleSel_Result>("RelUserRoleSel");
        }
    
        public virtual int RelUserRoleSi(Nullable<int> cCMSID, Nullable<int> userCCMSID, Nullable<int> rolId)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            var userCCMSIDParameter = userCCMSID.HasValue ?
                new ObjectParameter("UserCCMSID", userCCMSID) :
                new ObjectParameter("UserCCMSID", typeof(int));
    
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RelUserRoleSi", cCMSIDParameter, userCCMSIDParameter, rolIdParameter);
        }
    
        public virtual int RelUserRoleSu(Nullable<int> cCMSID, Nullable<int> relUserRoleId, Nullable<int> userCCMSID, Nullable<int> rolId, Nullable<bool> active)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            var relUserRoleIdParameter = relUserRoleId.HasValue ?
                new ObjectParameter("RelUserRoleId", relUserRoleId) :
                new ObjectParameter("RelUserRoleId", typeof(int));
    
            var userCCMSIDParameter = userCCMSID.HasValue ?
                new ObjectParameter("UserCCMSID", userCCMSID) :
                new ObjectParameter("UserCCMSID", typeof(int));
    
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RelUserRoleSu", cCMSIDParameter, relUserRoleIdParameter, userCCMSIDParameter, rolIdParameter, activeParameter);
        }
    
        public virtual ObjectResult<TraAPTerminationSel_Result> TraAPTerminationSel(Nullable<int> cCMSID)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraAPTerminationSel_Result>("TraAPTerminationSel", cCMSIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TraAPTerminationSi(Nullable<int> cCMSID, string fechaUltimaDeLaboras, Nullable<int> terminationTypeId, Nullable<int> motiveId, Nullable<bool> responsabilidadPatronal, Nullable<bool> recontratable, Nullable<bool> entregaGafeteId, Nullable<bool> entregaGafeteParqueo, Nullable<bool> entregaTarjetaDeAcceso, Nullable<bool> entregaHeadset, string observaciones, string comentarios, Nullable<int> cCMSIDUser, string iPAdrs, Nullable<bool> preAviso)
        {
            var cCMSIDParameter = cCMSID.HasValue ?
                new ObjectParameter("CCMSID", cCMSID) :
                new ObjectParameter("CCMSID", typeof(int));
    
            var fechaUltimaDeLaborasParameter = fechaUltimaDeLaboras != null ?
                new ObjectParameter("FechaUltimaDeLaboras", fechaUltimaDeLaboras) :
                new ObjectParameter("FechaUltimaDeLaboras", typeof(string));
    
            var terminationTypeIdParameter = terminationTypeId.HasValue ?
                new ObjectParameter("TerminationTypeId", terminationTypeId) :
                new ObjectParameter("TerminationTypeId", typeof(int));
    
            var motiveIdParameter = motiveId.HasValue ?
                new ObjectParameter("MotiveId", motiveId) :
                new ObjectParameter("MotiveId", typeof(int));
    
            var responsabilidadPatronalParameter = responsabilidadPatronal.HasValue ?
                new ObjectParameter("ResponsabilidadPatronal", responsabilidadPatronal) :
                new ObjectParameter("ResponsabilidadPatronal", typeof(bool));
    
            var recontratableParameter = recontratable.HasValue ?
                new ObjectParameter("Recontratable", recontratable) :
                new ObjectParameter("Recontratable", typeof(bool));
    
            var entregaGafeteIdParameter = entregaGafeteId.HasValue ?
                new ObjectParameter("EntregaGafeteId", entregaGafeteId) :
                new ObjectParameter("EntregaGafeteId", typeof(bool));
    
            var entregaGafeteParqueoParameter = entregaGafeteParqueo.HasValue ?
                new ObjectParameter("EntregaGafeteParqueo", entregaGafeteParqueo) :
                new ObjectParameter("EntregaGafeteParqueo", typeof(bool));
    
            var entregaTarjetaDeAccesoParameter = entregaTarjetaDeAcceso.HasValue ?
                new ObjectParameter("EntregaTarjetaDeAcceso", entregaTarjetaDeAcceso) :
                new ObjectParameter("EntregaTarjetaDeAcceso", typeof(bool));
    
            var entregaHeadsetParameter = entregaHeadset.HasValue ?
                new ObjectParameter("EntregaHeadset", entregaHeadset) :
                new ObjectParameter("EntregaHeadset", typeof(bool));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var cCMSIDUserParameter = cCMSIDUser.HasValue ?
                new ObjectParameter("CCMSIDUser", cCMSIDUser) :
                new ObjectParameter("CCMSIDUser", typeof(int));
    
            var iPAdrsParameter = iPAdrs != null ?
                new ObjectParameter("IPAdrs", iPAdrs) :
                new ObjectParameter("IPAdrs", typeof(string));
    
            var preAvisoParameter = preAviso.HasValue ?
                new ObjectParameter("PreAviso", preAviso) :
                new ObjectParameter("PreAviso", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TraAPTerminationSi", cCMSIDParameter, fechaUltimaDeLaborasParameter, terminationTypeIdParameter, motiveIdParameter, responsabilidadPatronalParameter, recontratableParameter, entregaGafeteIdParameter, entregaGafeteParqueoParameter, entregaTarjetaDeAccesoParameter, entregaHeadsetParameter, observacionesParameter, comentariosParameter, cCMSIDUserParameter, iPAdrsParameter, preAvisoParameter);
        }
    
        public virtual int TraCheckStatusAutoSu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TraCheckStatusAutoSu");
        }
    
        public virtual int TraClericalImagesIns(Nullable<int> catProDeproId, Nullable<int> actionId, Nullable<int> createdBy, string description, Nullable<bool> imagePlaceHolder, string path, string fileName, Nullable<bool> active, string imageUrl, string imageUrlGrid)
        {
            var catProDeproIdParameter = catProDeproId.HasValue ?
                new ObjectParameter("CatProDeproId", catProDeproId) :
                new ObjectParameter("CatProDeproId", typeof(int));
    
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var imagePlaceHolderParameter = imagePlaceHolder.HasValue ?
                new ObjectParameter("ImagePlaceHolder", imagePlaceHolder) :
                new ObjectParameter("ImagePlaceHolder", typeof(bool));
    
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var imageUrlParameter = imageUrl != null ?
                new ObjectParameter("ImageUrl", imageUrl) :
                new ObjectParameter("ImageUrl", typeof(string));
    
            var imageUrlGridParameter = imageUrlGrid != null ?
                new ObjectParameter("ImageUrlGrid", imageUrlGrid) :
                new ObjectParameter("ImageUrlGrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TraClericalImagesIns", catProDeproIdParameter, actionIdParameter, createdByParameter, descriptionParameter, imagePlaceHolderParameter, pathParameter, fileNameParameter, activeParameter, imageUrlParameter, imageUrlGridParameter);
        }
    
        public virtual ObjectResult<TraClericalImagesSelByEmployeeId_Result> TraClericalImagesSelByEmployeeId(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraClericalImagesSelByEmployeeId_Result>("TraClericalImagesSelByEmployeeId", employeeIdParameter);
        }
    
        public virtual ObjectResult<TraGeneraArchivoSel_Result> TraGeneraArchivoSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraGeneraArchivoSel_Result>("TraGeneraArchivoSel");
        }
    
        public virtual ObjectResult<TraProgrammingSel_Result> TraProgrammingSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraProgrammingSel_Result>("TraProgrammingSel");
        }
    
        public virtual int TraProgrammingSu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TraProgrammingSu");
        }
    
        public virtual ObjectResult<TraRepositionCMB_Result> TraRepositionCMB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraRepositionCMB_Result>("TraRepositionCMB");
        }
    
        public virtual ObjectResult<Nullable<int>> TraRepositionSi(Nullable<int> userEmployeeId, Nullable<int> employeeId, Nullable<int> repositionNumberId, Nullable<int> realBadgeNumber, Nullable<int> oldBadgenumber, Nullable<int> actionId)
        {
            var userEmployeeIdParameter = userEmployeeId.HasValue ?
                new ObjectParameter("UserEmployeeId", userEmployeeId) :
                new ObjectParameter("UserEmployeeId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var repositionNumberIdParameter = repositionNumberId.HasValue ?
                new ObjectParameter("RepositionNumberId", repositionNumberId) :
                new ObjectParameter("RepositionNumberId", typeof(int));
    
            var realBadgeNumberParameter = realBadgeNumber.HasValue ?
                new ObjectParameter("RealBadgeNumber", realBadgeNumber) :
                new ObjectParameter("RealBadgeNumber", typeof(int));
    
            var oldBadgenumberParameter = oldBadgenumber.HasValue ?
                new ObjectParameter("OldBadgenumber", oldBadgenumber) :
                new ObjectParameter("OldBadgenumber", typeof(int));
    
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TraRepositionSi", userEmployeeIdParameter, employeeIdParameter, repositionNumberIdParameter, realBadgeNumberParameter, oldBadgenumberParameter, actionIdParameter);
        }
    
        public virtual int TraTerminationAutoSi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TraTerminationAutoSi");
        }
    
        public virtual ObjectResult<TraTerminationSel_Result> TraTerminationSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraTerminationSel_Result>("TraTerminationSel");
        }
    
        public virtual int TraTransitionAutoSi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TraTransitionAutoSi");
        }
    }
}
