//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASN.Models
{
    using System;
    
    public partial class ReportePendientesAutorizarYRechazados_Result1
    {
        public string PeriodoNomina { get; set; }
        public int FolioSolicitud { get; set; }
        public Nullable<int> Incidencias { get; set; }
        public string Location_Name { get; set; }
        public string Concepto { get; set; }
        public string Estatus { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Autorizaciones_Pendientes { get; set; }
        public string Autorizador_Que_Rechaza { get; set; }
        public string Motivo_Del_Rechazo { get; set; }
    }
}
