/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Perfil_Ident]
      ,[NombrePerfilEmpleados]
      ,[Country_Ident]
      ,[City_Ident]
      ,[Location_Ident]
      ,[Client_Ident]
      ,[Program_Ident]
      ,[Contract_Type_Ident]
      ,[ConceptoId]
      ,[TipoAccesoId]
      ,[Active]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[DeactivatedDate]
      ,[DeactivatedBy]
      ,[LastModifiedBy]
      ,[LastModifiedDate]
      ,[LastModifiedFromPCName]
  FROM [ASN3].[app620].[CatPerfilEmpleados]
  
  SELECT * FROM [app620].[RelPerfilEmpleadosConceptos]
